//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysResource() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysResource", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 預設應用系統 的當地語系化字串。
        /// </summary>
        internal static string Combobox_DefaultSysID {
            get {
                return ResourceManager.GetString("Combobox_DefaultSysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電子資料交換連線字串檔 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemEDICon {
            get {
                return ResourceManager.GetString("TabText_SystemEDICon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電子資料交換 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemEDIFlow {
            get {
                return ResourceManager.GetString("TabText_SystemEDIFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電子資料交換紀錄檔 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemEDIFlowLog {
            get {
                return ResourceManager.GetString("TabText_SystemEDIFlowLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電子資料交換工作檔 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemEDIJob {
            get {
                return ResourceManager.GetString("TabText_SystemEDIJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電子資料交換工作紀錄檔 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemEDIJobLog {
            get {
                return ResourceManager.GetString("TabText_SystemEDIJobLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 事件訂閱 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemEvent {
            get {
                return ResourceManager.GetString("TabText_SystemEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 事件紀錄 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemEventEDI {
            get {
                return ResourceManager.GetString("TabText_SystemEventEDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 事件群組 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemEventGroup {
            get {
                return ResourceManager.GetString("TabText_SystemEventGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 事件紀錄清單 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemEventTargetEDI {
            get {
                return ResourceManager.GetString("TabText_SystemEventTargetEDI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 事件發送 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemEventTargetSend {
            get {
                return ResourceManager.GetString("TabText_SystemEventTargetSend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能清單 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemFun {
            get {
                return ResourceManager.GetString("TabText_SystemFun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能清單指派 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemFunAssign {
            get {
                return ResourceManager.GetString("TabText_SystemFunAssign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能清單明細 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemFunDetail {
            get {
                return ResourceManager.GetString("TabText_SystemFunDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能群組 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemFunGroup {
            get {
                return ResourceManager.GetString("TabText_SystemFunGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能選單 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemFunMenu {
            get {
                return ResourceManager.GetString("TabText_SystemFunMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料權限 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemPurview {
            get {
                return ResourceManager.GetString("TabText_SystemPurview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統角色 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemRole {
            get {
                return ResourceManager.GetString("TabText_SystemRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統設定 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemSetting {
            get {
                return ResourceManager.GetString("TabText_SystemSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 User Function Authorize 的當地語系化字串。
        /// </summary>
        internal static string TabText_UserFunction {
            get {
                return ResourceManager.GetString("TabText_UserFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者權限 的當地語系化字串。
        /// </summary>
        internal static string TabText_UserRoleFun {
            get {
                return ResourceManager.GetString("TabText_UserRoleFun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 User Role Authorize 的當地語系化字串。
        /// </summary>
        internal static string TabText_UserRoleFunDetail {
            get {
                return ResourceManager.GetString("TabText_UserRoleFunDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者外部應用系統權限 的當地語系化字串。
        /// </summary>
        internal static string TabText_UserSystem {
            get {
                return ResourceManager.GetString("TabText_UserSystem", resourceCulture);
            }
        }
    }
}
