//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysSystemSettingDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysSystemSettingDetail() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysSystemSettingDetail", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除系統設定明細失敗&lt;br /&gt;尚有：{0} 使用此項設定 的當地語系化字串。
        /// </summary>
        internal static string DeleteSystemSettingDetailResult_DataExist {
            get {
                return ResourceManager.GetString("DeleteSystemSettingDetailResult_DataExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除系統設定明細失敗 的當地語系化字串。
        /// </summary>
        internal static string DeleteSystemSettingDetailResult_Failure {
            get {
                return ResourceManager.GetString("DeleteSystemSettingDetailResult_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯系統設定明細失敗 的當地語系化字串。
        /// </summary>
        internal static string EditSystemSettingDetailResult_Failure {
            get {
                return ResourceManager.GetString("EditSystemSettingDetailResult_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統加密代碼 的當地語系化字串。
        /// </summary>
        internal static string Label_ENSysID {
            get {
                return ResourceManager.GetString("Label_ENSysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否停用 的當地語系化字串。
        /// </summary>
        internal static string Label_IsDisable {
            get {
                return ResourceManager.GetString("Label_IsDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否是外部系統 的當地語系化字串。
        /// </summary>
        internal static string Label_IsOutsourcing {
            get {
                return ResourceManager.GetString("Label_IsOutsourcing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序 的當地語系化字串。
        /// </summary>
        internal static string Label_SortOrder {
            get {
                return ResourceManager.GetString("Label_SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統圖示 的當地語系化字串。
        /// </summary>
        internal static string Label_SysIcon {
            get {
                return ResourceManager.GetString("Label_SysIcon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_SysID {
            get {
                return ResourceManager.GetString("Label_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統首頁位置 的當地語系化字串。
        /// </summary>
        internal static string Label_SysIndexPath {
            get {
                return ResourceManager.GetString("Label_SysIndexPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統金鑰 的當地語系化字串。
        /// </summary>
        internal static string Label_SysKey {
            get {
                return ResourceManager.GetString("Label_SysKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統名稱(英) 的當地語系化字串。
        /// </summary>
        internal static string Label_SysNMENUS {
            get {
                return ResourceManager.GetString("Label_SysNMENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統名稱(日) 的當地語系化字串。
        /// </summary>
        internal static string Label_SysNMJAJP {
            get {
                return ResourceManager.GetString("Label_SysNMJAJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統名稱(泰) 的當地語系化字串。
        /// </summary>
        internal static string Label_SysNMTHTH {
            get {
                return ResourceManager.GetString("Label_SysNMTHTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統名稱(簡) 的當地語系化字串。
        /// </summary>
        internal static string Label_SysNMZHCN {
            get {
                return ResourceManager.GetString("Label_SysNMZHCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統名稱(繁) 的當地語系化字串。
        /// </summary>
        internal static string Label_SysNMZHTW {
            get {
                return ResourceManager.GetString("Label_SysNMZHTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 管理使用者代碼 的當地語系化字串。
        /// </summary>
        internal static string Label_UserID {
            get {
                return ResourceManager.GetString("Label_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統設定明細已存在 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_AddSystemSettingDetailExist {
            get {
                return ResourceManager.GetString("SystemMsg_AddSystemSettingDetailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得系統設定明細列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSystemSettingDetail {
            get {
                return ResourceManager.GetString("SystemMsg_GetSystemSettingDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 此使用者不具管理{0}權限 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_NoAuthorization {
            get {
                return ResourceManager.GetString("SystemMsg_NoAuthorization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統設定明細 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemSettingDetail {
            get {
                return ResourceManager.GetString("TabText_SystemSettingDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統圖示上傳失敗 的當地語系化字串。
        /// </summary>
        internal static string UpdateSysIconPathResult_Failure {
            get {
                return ResourceManager.GetString("UpdateSysIconPathResult_Failure", resourceCulture);
            }
        }
    }
}
