//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysSystemRoleDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysSystemRoleDetail() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysSystemRoleDetail", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除系統角色明細失敗 的當地語系化字串。
        /// </summary>
        internal static string DeleteSystemRoleDetailResult_Failure {
            get {
                return ResourceManager.GetString("DeleteSystemRoleDetailResult_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯系統角色明細失敗 的當地語系化字串。
        /// </summary>
        internal static string EditSystemRoleDetailResult_Failure {
            get {
                return ResourceManager.GetString("EditSystemRoleDetailResult_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色代碼 的當地語系化字串。
        /// </summary>
        internal static string Label_RoleID {
            get {
                return ResourceManager.GetString("Label_RoleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色名稱(英) 的當地語系化字串。
        /// </summary>
        internal static string Label_RoleNMENUS {
            get {
                return ResourceManager.GetString("Label_RoleNMENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色名稱(日) 的當地語系化字串。
        /// </summary>
        internal static string Label_RoleNMJAJP {
            get {
                return ResourceManager.GetString("Label_RoleNMJAJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色名稱(泰) 的當地語系化字串。
        /// </summary>
        internal static string Label_RoleNMTHTH {
            get {
                return ResourceManager.GetString("Label_RoleNMTHTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色名稱(簡) 的當地語系化字串。
        /// </summary>
        internal static string Label_RoleNMZHCN {
            get {
                return ResourceManager.GetString("Label_RoleNMZHCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色名稱(繁) 的當地語系化字串。
        /// </summary>
        internal static string Label_RoleNMZHTW {
            get {
                return ResourceManager.GetString("Label_RoleNMZHTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_SysID {
            get {
                return ResourceManager.GetString("Label_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統角色明細已存在 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_AddSystemRoleDetailExist {
            get {
                return ResourceManager.GetString("SystemMsg_AddSystemRoleDetailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得系統角色明細列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSystemRoleDetail {
            get {
                return ResourceManager.GetString("SystemMsg_GetSystemRoleDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得應用系統列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysUserSystemSysIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysUserSystemSysIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統角色明細 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemRoleDetail {
            get {
                return ResourceManager.GetString("TabText_SystemRoleDetail", resourceCulture);
            }
        }
    }
}
