//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysSystemFun {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysSystemFun() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysSystemFun", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 功能清單儲存失敗 的當地語系化字串。
        /// </summary>
        internal static string EditSystemFunResult_Failure {
            get {
                return ResourceManager.GetString("EditSystemFunResult_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能清單儲存成功 的當地語系化字串。
        /// </summary>
        internal static string EditSystemFunResult_Success {
            get {
                return ResourceManager.GetString("EditSystemFunResult_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選取數量超出限制，上限為{0}筆 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_ExceedDataCountLimit {
            get {
                return ResourceManager.GetString("JsMsg_ExceedDataCountLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得功能群組列表 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_GetSystemFunControllerIDList {
            get {
                return ResourceManager.GetString("JsMsg_GetSystemFunControllerIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得功能選單列表 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_GetSystemFunMenuList {
            get {
                return ResourceManager.GetString("JsMsg_GetSystemFunMenuList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請先選取要處理的資料 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_PickData {
            get {
                return ResourceManager.GetString("JsMsg_PickData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 停用 的當地語系化字串。
        /// </summary>
        internal static string Label_Disable {
            get {
                return ResourceManager.GetString("Label_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 啟用 的當地語系化字串。
        /// </summary>
        internal static string Label_Enable {
            get {
                return ResourceManager.GetString("Label_Enable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能名稱 的當地語系化字串。
        /// </summary>
        internal static string Label_FunAction {
            get {
                return ResourceManager.GetString("Label_FunAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能群組 的當地語系化字串。
        /// </summary>
        internal static string Label_FunGroup {
            get {
                return ResourceManager.GetString("Label_FunGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能群組名稱 % 的當地語系化字串。
        /// </summary>
        internal static string Label_FunGroupNM {
            get {
                return ResourceManager.GetString("Label_FunGroupNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能選單 的當地語系化字串。
        /// </summary>
        internal static string Label_FunMenu {
            get {
                return ResourceManager.GetString("Label_FunMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能選單應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_FunMenuSysID {
            get {
                return ResourceManager.GetString("Label_FunMenuSysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能名稱 % 的當地語系化字串。
        /// </summary>
        internal static string Label_FunNM {
            get {
                return ResourceManager.GetString("Label_FunNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料權限 的當地語系化字串。
        /// </summary>
        internal static string Label_PurviewID {
            get {
                return ResourceManager.GetString("Label_PurviewID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統(子系統) 的當地語系化字串。
        /// </summary>
        internal static string Label_SubSysID {
            get {
                return ResourceManager.GetString("Label_SubSysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_SysID {
            get {
                return ResourceManager.GetString("Label_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得功能群組列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemFunControllerIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemFunControllerIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得功能選單列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemFunMenuList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemFunMenuList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得功能名稱應用系統列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemFunNameList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemFunNameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得資料權限列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemPurviewIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemPurviewIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得功能路徑-應用系統列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemSubsysIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemSubsysIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得功能選單應用系統列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemSysIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemSysIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得功能清單列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSystemFunList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSystemFunList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得應用系統列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysUserSystemSysIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysUserSystemSysIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 停用 的當地語系化字串。
        /// </summary>
        internal static string Table_Disable {
            get {
                return ResourceManager.GetString("Table_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能群組 的當地語系化字串。
        /// </summary>
        internal static string Table_FunGroup {
            get {
                return ResourceManager.GetString("Table_FunGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能選單 的當地語系化字串。
        /// </summary>
        internal static string Table_FunMenuNM {
            get {
                return ResourceManager.GetString("Table_FunMenuNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能名稱 的當地語系化字串。
        /// </summary>
        internal static string Table_FunNM {
            get {
                return ResourceManager.GetString("Table_FunNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能路徑 的當地語系化字串。
        /// </summary>
        internal static string Table_FunPath {
            get {
                return ResourceManager.GetString("Table_FunPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 外部使用 的當地語系化字串。
        /// </summary>
        internal static string Table_OutSide {
            get {
                return ResourceManager.GetString("Table_OutSide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序 的當地語系化字串。
        /// </summary>
        internal static string Table_SortOrder {
            get {
                return ResourceManager.GetString("Table_SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統(子系統) 的當地語系化字串。
        /// </summary>
        internal static string Table_SubSysNM {
            get {
                return ResourceManager.GetString("Table_SubSysNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Table_SysNM {
            get {
                return ResourceManager.GetString("Table_SysNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新時間 的當地語系化字串。
        /// </summary>
        internal static string Table_UpdDT {
            get {
                return ResourceManager.GetString("Table_UpdDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新人員 的當地語系化字串。
        /// </summary>
        internal static string Table_UpdUserNM {
            get {
                return ResourceManager.GetString("Table_UpdUserNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 複製 的當地語系化字串。
        /// </summary>
        internal static string Text_Copy {
            get {
                return ResourceManager.GetString("Text_Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 明細 的當地語系化字串。
        /// </summary>
        internal static string Text_Detail {
            get {
                return ResourceManager.GetString("Text_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 選取 的當地語系化字串。
        /// </summary>
        internal static string Text_Pick {
            get {
                return ResourceManager.GetString("Text_Pick", resourceCulture);
            }
        }
    }
}
