//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysSystemFunMenuDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysSystemFunMenuDetail() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysSystemFunMenuDetail", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除功能選單明細失敗&lt;br /&gt;尚有：{0} 使用此項設定 的當地語系化字串。
        /// </summary>
        internal static string DeleteSystemFunMenuDetailResult_DataExist {
            get {
                return ResourceManager.GetString("DeleteSystemFunMenuDetailResult_DataExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除功能選單明細失敗 的當地語系化字串。
        /// </summary>
        internal static string DeleteSystemFunMenuDetailResult_Failure {
            get {
                return ResourceManager.GetString("DeleteSystemFunMenuDetailResult_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯功能選單明細失敗 的當地語系化字串。
        /// </summary>
        internal static string EditSystemFunMenuDetailResult_Failure {
            get {
                return ResourceManager.GetString("EditSystemFunMenuDetailResult_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預設選單編號 的當地語系化字串。
        /// </summary>
        internal static string Label_DefaultMenuID {
            get {
                return ResourceManager.GetString("Label_DefaultMenuID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能選單 的當地語系化字串。
        /// </summary>
        internal static string Label_FunMenu {
            get {
                return ResourceManager.GetString("Label_FunMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能選單名稱(英) 的當地語系化字串。
        /// </summary>
        internal static string Label_FunMenuNMENUS {
            get {
                return ResourceManager.GetString("Label_FunMenuNMENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能選單名稱(日) 的當地語系化字串。
        /// </summary>
        internal static string Label_FunMenuNMJAJP {
            get {
                return ResourceManager.GetString("Label_FunMenuNMJAJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能選單名稱(泰) 的當地語系化字串。
        /// </summary>
        internal static string Label_FunMenuNMTHTH {
            get {
                return ResourceManager.GetString("Label_FunMenuNMTHTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能選單名稱(簡) 的當地語系化字串。
        /// </summary>
        internal static string Label_FunMenuNMZHCN {
            get {
                return ResourceManager.GetString("Label_FunMenuNMZHCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能選單名稱(繁) 的當地語系化字串。
        /// </summary>
        internal static string Label_FunMenuNMZHTW {
            get {
                return ResourceManager.GetString("Label_FunMenuNMZHTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否停用 的當地語系化字串。
        /// </summary>
        internal static string Label_IsDisable {
            get {
                return ResourceManager.GetString("Label_IsDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序 的當地語系化字串。
        /// </summary>
        internal static string Label_SortOrder {
            get {
                return ResourceManager.GetString("Label_SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_SysID {
            get {
                return ResourceManager.GetString("Label_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能選單明細已存在 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_AddSystemFunMenuDetailExist {
            get {
                return ResourceManager.GetString("SystemMsg_AddSystemFunMenuDetailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得功能選單明細列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSystemFunMenuDetail {
            get {
                return ResourceManager.GetString("SystemMsg_GetSystemFunMenuDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得應用系統列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysUserSystemSysIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysUserSystemSysIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能選單明細 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemFunMenuDetail {
            get {
                return ResourceManager.GetString("TabText_SystemFunMenuDetail", resourceCulture);
            }
        }
    }
}
