//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysUserSettingDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysUserSettingDetail() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysUserSettingDetail", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯帳號資料明細失敗 的當地語系化字串。
        /// </summary>
        internal static string EditUserSettingDetailResult_Failure {
            get {
                return ResourceManager.GetString("EditUserSettingDetailResult_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇性別 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_UserGender {
            get {
                return ResourceManager.GetString("JsMsg_UserGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 狀態 的當地語系化字串。
        /// </summary>
        internal static string Label_AccountStatus {
            get {
                return ResourceManager.GetString("Label_AccountStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統加密代碼 的當地語系化字串。
        /// </summary>
        internal static string Label_ENSysID {
            get {
                return ResourceManager.GetString("Label_ENSysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 停用 的當地語系化字串。
        /// </summary>
        internal static string Label_IsDisable {
            get {
                return ResourceManager.GetString("Label_IsDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 可設定B2P帳號 的當地語系化字串。
        /// </summary>
        internal static string Label_IsGrantor {
            get {
                return ResourceManager.GetString("Label_IsGrantor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 權限 的當地語系化字串。
        /// </summary>
        internal static string Label_Permission {
            get {
                return ResourceManager.GetString("Label_Permission", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備註 的當地語系化字串。
        /// </summary>
        internal static string Label_Remark {
            get {
                return ResourceManager.GetString("Label_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統金鑰 的當地語系化字串。
        /// </summary>
        internal static string Label_SysKey {
            get {
                return ResourceManager.GetString("Label_SysKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新 的當地語系化字串。
        /// </summary>
        internal static string Label_UpdInfor {
            get {
                return ResourceManager.GetString("Label_UpdInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Mail 的當地語系化字串。
        /// </summary>
        internal static string Label_UserEmail {
            get {
                return ResourceManager.GetString("Label_UserEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 性別 的當地語系化字串。
        /// </summary>
        internal static string Label_UserGender {
            get {
                return ResourceManager.GetString("Label_UserGender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號 的當地語系化字串。
        /// </summary>
        internal static string Label_UserID {
            get {
                return ResourceManager.GetString("Label_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 姓名 的當地語系化字串。
        /// </summary>
        internal static string Label_UserNM {
            get {
                return ResourceManager.GetString("Label_UserNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼 的當地語系化字串。
        /// </summary>
        internal static string Label_UserPWD {
            get {
                return ResourceManager.GetString("Label_UserPWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 (空白表示密碼不做異動，或請輸入欲變更的新密碼) 的當地語系化字串。
        /// </summary>
        internal static string Label_UserPWDRemind {
            get {
                return ResourceManager.GetString("Label_UserPWDRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電話 的當地語系化字串。
        /// </summary>
        internal static string Label_UserTel {
            get {
                return ResourceManager.GetString("Label_UserTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 職稱 的當地語系化字串。
        /// </summary>
        internal static string Label_UserTitle {
            get {
                return ResourceManager.GetString("Label_UserTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 女 的當地語系化字串。
        /// </summary>
        internal static string Radio_Female {
            get {
                return ResourceManager.GetString("Radio_Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 男 的當地語系化字串。
        /// </summary>
        internal static string Radio_Male {
            get {
                return ResourceManager.GetString("Radio_Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號資料明細已存在 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_AddUserSettingDetailExist {
            get {
                return ResourceManager.GetString("SystemMsg_AddUserSettingDetailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能選單產生失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GenerateFailure {
            get {
                return ResourceManager.GetString("SystemMsg_GenerateFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得授權人帳號資料明細 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSystemUserDetail {
            get {
                return ResourceManager.GetString("SystemMsg_GetSystemUserDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得帳號資料明細 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetUserSettingDetail {
            get {
                return ResourceManager.GetString("SystemMsg_GetUserSettingDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 帳號資料明細 的當地語系化字串。
        /// </summary>
        internal static string TabText_UserSettingDetail {
            get {
                return ResourceManager.GetString("TabText_UserSettingDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Mail格式不正確 的當地語系化字串。
        /// </summary>
        internal static string ValidationMailFormatResult_Failure {
            get {
                return ResourceManager.GetString("ValidationMailFormatResult_Failure", resourceCulture);
            }
        }
    }
}
