namespace LionTech.InAPI.SYSMGTAPI.Domain.Enums
{
    public enum EnumMongoDocName
    {
        SYS_USER_SYSTEM_NOTIFICATIONS, SYS_SYSTEM_ROLE_CONDTION,
        LOG_USER_SYSTEM_ROLE_APPLY, LOG_USER_FUN_APPLY,
        APP_USER_PUSH, LOG_APP_USER_PUSH,
        APP_TOPIC_PUSH, LOG_APP_TOPIC_PUSH,
        LOG_SYS_SYSTEM_FUN_ELM, LOG_SYS_SYSTEM_ROLE_FUN_ELM, LOG_USER_FUN_ELM,
        LOG_USER_TRACE_ACTION, LOG_SYS_TRUST_IP, LOG_SYS_SYSTEM_FUN, LOG_SYS_SYSTEM_FUN_GROUP,
        LOG_SYS_SYSTEM_LINE, LOG_SYS_SYSTEM_LINE_RECEIVER, LOG_SYS_SYSTEM_ROLE, LOG_SYS_SYSTEM_ROLE_CONDTION,
        LOG_SYS_SYSTEM_ROLE_FLOW, LOG_SYS_SYSTEM_ROLE_FUN, LOG_SYS_SYSTEM_ROLE_GROUP, LOG_SYS_SYSTEM_ROLE_GROUP_COLLECT,
        LOG_SYS_SYSTEM_ROLE_GROUP_CONDITION, LOG_SYS_SYSTEM_ROLE_NODE, LOG_SYS_SYSTEM_ROLE_SIG, LOG_SYS_SYSTEM_WF_DOC,
        LOG_SYS_SYSTEM_WF_FLOW, LOG_SYS_SYSTEM_WF_FLOW_GROUP, LOG_SYS_SYSTEM_WF_NEXT, LOG_SYS_SYSTEM_WF_NODE, LOG_SYS_SYSTEM_WF_SIG,
        LOG_USER_ACCESS, LOG_USER_ACCOUNT, LOG_USER_FUN, LOG_USER_LOGIN, LOG_USER_PURVIEW, LOG_USER_PURVIEW_APPLY, LOG_USER_PWD,
        LOG_WF_FLOW
    }
}