//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysADSReport {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysADSReport() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysADSReport", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統-角色對應功能 的當地語系化字串。
        /// </summary>
        internal static string ComboBox_SyRoleToFunction {
            get {
                return ResourceManager.GetString("ComboBox_SyRoleToFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統-單一功能授予 的當地語系化字串。
        /// </summary>
        internal static string ComboBox_SySingleFunctionAwarded {
            get {
                return ResourceManager.GetString("ComboBox_SySingleFunctionAwarded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者-最後登入時間 的當地語系化字串。
        /// </summary>
        internal static string ComboBox_SysLastTime {
            get {
                return ResourceManager.GetString("ComboBox_SysLastTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統-報表預設權限(搭配職級) 的當地語系化字串。
        /// </summary>
        internal static string ComboBox_SysReportToPermissions {
            get {
                return ResourceManager.GetString("ComboBox_SysReportToPermissions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統-使用者對應角色 的當地語系化字串。
        /// </summary>
        internal static string ComboBox_SyUserToFunction {
            get {
                return ResourceManager.GetString("ComboBox_SyUserToFunction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 處理中 請稍候... 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_ProccessWaiting {
            get {
                return ResourceManager.GetString("JsMsg_ProccessWaiting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 報表類型 的當地語系化字串。
        /// </summary>
        internal static string Label_ReportType {
            get {
                return ResourceManager.GetString("Label_ReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用類型 的當地語系化字串。
        /// </summary>
        internal static string Label_SystemType {
            get {
                return ResourceManager.GetString("Label_SystemType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得稽核報告失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetADSReportList_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_GetADSReportList_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得應用系統列表失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemSysIDList_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemSysIDList_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能 的當地語系化字串。
        /// </summary>
        internal static string Table_Function {
            get {
                return ResourceManager.GetString("Table_Function", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否停用 的當地語系化字串。
        /// </summary>
        internal static string Table_IsDisable {
            get {
                return ResourceManager.GetString("Table_IsDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否離職 的當地語系化字串。
        /// </summary>
        internal static string Table_IsLeft {
            get {
                return ResourceManager.GetString("Table_IsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 最後登入時間 的當地語系化字串。
        /// </summary>
        internal static string Table_LastTime {
            get {
                return ResourceManager.GetString("Table_LastTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色 的當地語系化字串。
        /// </summary>
        internal static string Table_Role {
            get {
                return ResourceManager.GetString("Table_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統 的當地語系化字串。
        /// </summary>
        internal static string Table_SysID {
            get {
                return ResourceManager.GetString("Table_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統角色 的當地語系化字串。
        /// </summary>
        internal static string Table_SysRoleID {
            get {
                return ResourceManager.GetString("Table_SysRoleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單位 的當地語系化字串。
        /// </summary>
        internal static string Table_Unit {
            get {
                return ResourceManager.GetString("Table_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者 的當地語系化字串。
        /// </summary>
        internal static string Table_UserID {
            get {
                return ResourceManager.GetString("Table_UserID", resourceCulture);
            }
        }
    }
}
