//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysLatestUseIP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysLatestUseIP() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysLatestUseIP", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 IP位置 的當地語系化字串。
        /// </summary>
        internal static string Label_IPAddress {
            get {
                return ResourceManager.GetString("Label_IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得IP最後使用資訊失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetLatestUseIPInfo_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_GetLatestUseIPInfo_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 IP格式錯誤 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_IPAddressFormate_Error {
            get {
                return ResourceManager.GetString("SystemMsg_IPAddressFormate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司 的當地語系化字串。
        /// </summary>
        internal static string Table_Comp {
            get {
                return ResourceManager.GetString("Table_Comp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司電話 的當地語系化字串。
        /// </summary>
        internal static string Table_CompTel {
            get {
                return ResourceManager.GetString("Table_CompTel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 分機 的當地語系化字串。
        /// </summary>
        internal static string Table_CompTelExt {
            get {
                return ResourceManager.GetString("Table_CompTelExt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ERP-工作 的當地語系化字串。
        /// </summary>
        internal static string Table_ErpJob {
            get {
                return ResourceManager.GetString("Table_ErpJob", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 IP位置 的當地語系化字串。
        /// </summary>
        internal static string Table_IPAddress {
            get {
                return ResourceManager.GetString("Table_IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單位 的當地語系化字串。
        /// </summary>
        internal static string Table_Unit {
            get {
                return ResourceManager.GetString("Table_Unit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者 的當地語系化字串。
        /// </summary>
        internal static string Table_User {
            get {
                return ResourceManager.GetString("Table_User", resourceCulture);
            }
        }
    }
}
