//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別為自動產生，方法是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysSystemAPIGroupDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysSystemAPIGroupDetail() {
        }
        
        /// <summary>
        ///   傳回這個類別所使用的快取 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysSystemAPIGroupDetail", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除API群組明細失敗&lt;br /&gt;尚有：{0} 使用此項設定 的當地語系化字串。
        /// </summary>
        internal static string DeleteSystemAPIGroupDetailResult_DataExist {
            get {
                return ResourceManager.GetString("DeleteSystemAPIGroupDetailResult_DataExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除API群組明細失敗 的當地語系化字串。
        /// </summary>
        internal static string DeleteSystemAPIGroupDetailResult_Failure {
            get {
                return ResourceManager.GetString("DeleteSystemAPIGroupDetailResult_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯API群組明細失敗 的當地語系化字串。
        /// </summary>
        internal static string EditSystemAPIGroupDetailResult_Failure {
            get {
                return ResourceManager.GetString("EditSystemAPIGroupDetailResult_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 API群組 的當地語系化字串。
        /// </summary>
        internal static string Label_APIGroup {
            get {
                return ResourceManager.GetString("Label_APIGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 API群組名稱(英) 的當地語系化字串。
        /// </summary>
        internal static string Label_APIGroupENUS {
            get {
                return ResourceManager.GetString("Label_APIGroupENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 API群組名稱(日) 的當地語系化字串。
        /// </summary>
        internal static string Label_APIGroupJAJP {
            get {
                return ResourceManager.GetString("Label_APIGroupJAJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 API群組名稱(韓) 的當地語系化字串。
        /// </summary>
        internal static string Label_APIGroupKOKR {
            get {
                return ResourceManager.GetString("Label_APIGroupKOKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 API群組名稱(泰) 的當地語系化字串。
        /// </summary>
        internal static string Label_APIGroupTHTH {
            get {
                return ResourceManager.GetString("Label_APIGroupTHTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 API群組名稱(簡) 的當地語系化字串。
        /// </summary>
        internal static string Label_APIGroupZHCN {
            get {
                return ResourceManager.GetString("Label_APIGroupZHCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 API群組名稱(繁) 的當地語系化字串。
        /// </summary>
        internal static string Label_APIGroupZHTW {
            get {
                return ResourceManager.GetString("Label_APIGroupZHTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序 的當地語系化字串。
        /// </summary>
        internal static string Label_SortOrder {
            get {
                return ResourceManager.GetString("Label_SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_SysID {
            get {
                return ResourceManager.GetString("Label_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 API群組明細已存在 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_IsExistSystemAPIGroupDetail {
            get {
                return ResourceManager.GetString("SystemMsg_IsExistSystemAPIGroupDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得API群組明細列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_UnGetSystemAPIGroupDetail {
            get {
                return ResourceManager.GetString("SystemMsg_UnGetSystemAPIGroupDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得應用系統選單 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_UnGetUserSystemByIdList {
            get {
                return ResourceManager.GetString("SystemMsg_UnGetUserSystemByIdList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 API群組明細 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemAPIGroupDetail {
            get {
                return ResourceManager.GetString("TabText_SystemAPIGroupDetail", resourceCulture);
            }
        }
    }
}
