//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysSystemIPList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysSystemIPList() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysSystemIPList", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 API Server 的當地語系化字串。
        /// </summary>
        internal static string Checkbox_IsAPIServer {
            get {
                return ResourceManager.GetString("Checkbox_IsAPIServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 AP Server 的當地語系化字串。
        /// </summary>
        internal static string Checkbox_IsAPServer {
            get {
                return ResourceManager.GetString("Checkbox_IsAPServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 DB Server 的當地語系化字串。
        /// </summary>
        internal static string Checkbox_IsDBServer {
            get {
                return ResourceManager.GetString("Checkbox_IsDBServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 FILE Server 的當地語系化字串。
        /// </summary>
        internal static string Checkbox_IsFileServer {
            get {
                return ResourceManager.GetString("Checkbox_IsFileServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否對外 的當地語系化字串。
        /// </summary>
        internal static string Checkbox_IsOutsourcing {
            get {
                return ResourceManager.GetString("Checkbox_IsOutsourcing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除系統硬體架構清單失敗 的當地語系化字串。
        /// </summary>
        internal static string DeleteSystemIPListFailure {
            get {
                return ResourceManager.GetString("DeleteSystemIPListFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯系統硬體架構清單失敗 的當地語系化字串。
        /// </summary>
        internal static string EditSystemIPListFailure {
            get {
                return ResourceManager.GetString("EditSystemIPListFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入來源IP 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_IPAddress {
            get {
                return ResourceManager.GetString("JsMsg_IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 只能允許輸入英文、數字與一槓(-) 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_OnlyAllowEnglish {
            get {
                return ResourceManager.GetString("JsMsg_OnlyAllowEnglish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您輸入的應用系統、子系統與File Server已存在&lt;br/&gt;請將原先的File Server刪除再修改 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_SystemSubSystemFileServerSame {
            get {
                return ResourceManager.GetString("JsMsg_SystemSubSystemFileServerSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除 的當地語系化字串。
        /// </summary>
        internal static string Label_Delete {
            get {
                return ResourceManager.GetString("Label_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 伺服器資料夾位置 的當地語系化字串。
        /// </summary>
        internal static string Label_FolderPath {
            get {
                return ResourceManager.GetString("Label_FolderPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 來源IP 的當地語系化字串。
        /// </summary>
        internal static string Label_IPAddress {
            get {
                return ResourceManager.GetString("Label_IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否為API Server 的當地語系化字串。
        /// </summary>
        internal static string Label_IsAPIServer {
            get {
                return ResourceManager.GetString("Label_IsAPIServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否為AP Server 的當地語系化字串。
        /// </summary>
        internal static string Label_IsAPServer {
            get {
                return ResourceManager.GetString("Label_IsAPServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否為DB Server 的當地語系化字串。
        /// </summary>
        internal static string Label_IsDBServer {
            get {
                return ResourceManager.GetString("Label_IsDBServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否為FILE Server 的當地語系化字串。
        /// </summary>
        internal static string Label_IsFileServer {
            get {
                return ResourceManager.GetString("Label_IsFileServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否對外 的當地語系化字串。
        /// </summary>
        internal static string Label_IsOutsourcing {
            get {
                return ResourceManager.GetString("Label_IsOutsourcing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備註 的當地語系化字串。
        /// </summary>
        internal static string Label_Remark {
            get {
                return ResourceManager.GetString("Label_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 主機名稱 的當地語系化字串。
        /// </summary>
        internal static string Label_ServerNM {
            get {
                return ResourceManager.GetString("Label_ServerNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 伺服器用途/類型 的當地語系化字串。
        /// </summary>
        internal static string Label_ServerType {
            get {
                return ResourceManager.GetString("Label_ServerType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_SysID {
            get {
                return ResourceManager.GetString("Label_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用子系統 的當地語系化字串。
        /// </summary>
        internal static string Label_SystemSubsys {
            get {
                return ResourceManager.GetString("Label_SystemSubsys", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改 的當地語系化字串。
        /// </summary>
        internal static string Label_Update {
            get {
                return ResourceManager.GetString("Label_Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新時間 的當地語系化字串。
        /// </summary>
        internal static string Label_UpdDT {
            get {
                return ResourceManager.GetString("Label_UpdDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新人員 的當地語系化字串。
        /// </summary>
        internal static string Label_UpdUserNM {
            get {
                return ResourceManager.GetString("Label_UpdUserNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認要執行該筆有重複的資訊嗎? 的當地語系化字串。
        /// </summary>
        internal static string SysMsg_RepeatDataConfirm {
            get {
                return ResourceManager.GetString("SysMsg_RepeatDataConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得系統硬體架構清單 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSystemIPList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSystemIPList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統硬體架構清單 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemIPList {
            get {
                return ResourceManager.GetString("TabText_SystemIPList", resourceCulture);
            }
        }
    }
}
