//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysSRCProject {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysSRCProject() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysSRCProject", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 ---------------SVN專案--------------- 的當地語系化字串。
        /// </summary>
        internal static string ComboBox_IsSVN {
            get {
                return ResourceManager.GetString("ComboBox_IsSVN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ---------------非SVN專案--------------- 的當地語系化字串。
        /// </summary>
        internal static string ComboBox_NotSVN {
            get {
                return ResourceManager.GetString("ComboBox_NotSVN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 未有專案資料，請洽系統管理者 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_GetSRCProjectList {
            get {
                return ResourceManager.GetString("JsMsg_GetSRCProjectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 網域群組 的當地語系化字串。
        /// </summary>
        internal static string Label_DomainGroupID {
            get {
                return ResourceManager.GetString("Label_DomainGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 網域名稱 的當地語系化字串。
        /// </summary>
        internal static string Label_DomainName {
            get {
                return ResourceManager.GetString("Label_DomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 專案名稱 的當地語系化字串。
        /// </summary>
        internal static string Label_ProjectID {
            get {
                return ResourceManager.GetString("Label_ProjectID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得版本控管帳號列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSRCProjectList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSRCProjectList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 明細 的當地語系化字串。
        /// </summary>
        internal static string Text_Detail {
            get {
                return ResourceManager.GetString("Text_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 網域群組 的當地語系化字串。
        /// </summary>
        internal static string Text_DomainGroupID {
            get {
                return ResourceManager.GetString("Text_DomainGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 網域名稱 的當地語系化字串。
        /// </summary>
        internal static string Text_DomainName {
            get {
                return ResourceManager.GetString("Text_DomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否有讀取權限 的當地語系化字串。
        /// </summary>
        internal static string Text_IsRead {
            get {
                return ResourceManager.GetString("Text_IsRead", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否為SVN專案 的當地語系化字串。
        /// </summary>
        internal static string Text_IsSVN {
            get {
                return ResourceManager.GetString("Text_IsSVN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否有寫入權限 的當地語系化字串。
        /// </summary>
        internal static string Text_IsWrite {
            get {
                return ResourceManager.GetString("Text_IsWrite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 專案名稱 的當地語系化字串。
        /// </summary>
        internal static string Text_ProjectID {
            get {
                return ResourceManager.GetString("Text_ProjectID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 父專案名稱 的當地語系化字串。
        /// </summary>
        internal static string Text_ProjectParent {
            get {
                return ResourceManager.GetString("Text_ProjectParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備註 的當地語系化字串。
        /// </summary>
        internal static string Text_Remark {
            get {
                return ResourceManager.GetString("Text_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新時間 的當地語系化字串。
        /// </summary>
        internal static string Text_UpdDT {
            get {
                return ResourceManager.GetString("Text_UpdDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新人員 的當地語系化字串。
        /// </summary>
        internal static string Text_UpdUserID {
            get {
                return ResourceManager.GetString("Text_UpdUserID", resourceCulture);
            }
        }
    }
}
