//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別為自動產生，方法是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysSystemPurviewDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysSystemPurviewDetail() {
        }
        
        /// <summary>
        ///   傳回這個類別所使用的快取 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysSystemPurviewDetail", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除資料權限明細失敗&lt;br /&gt;尚有：{0} 使用此項設定 的當地語系化字串。
        /// </summary>
        internal static string DeleteSystemPurviewDetailResult_DataExist {
            get {
                return ResourceManager.GetString("DeleteSystemPurviewDetailResult_DataExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除資料權限明細失敗 的當地語系化字串。
        /// </summary>
        internal static string DeleteSystemPurviewDetailResult_Failure {
            get {
                return ResourceManager.GetString("DeleteSystemPurviewDetailResult_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯資料權限明細失敗 的當地語系化字串。
        /// </summary>
        internal static string EditSystemPurviewDetailResult_Failure {
            get {
                return ResourceManager.GetString("EditSystemPurviewDetailResult_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料權限 的當地語系化字串。
        /// </summary>
        internal static string Label_PurviewID {
            get {
                return ResourceManager.GetString("Label_PurviewID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料權限名稱(英) 的當地語系化字串。
        /// </summary>
        internal static string Label_PurviewNMENUS {
            get {
                return ResourceManager.GetString("Label_PurviewNMENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料權限名稱(日) 的當地語系化字串。
        /// </summary>
        internal static string Label_PurviewNMJAJP {
            get {
                return ResourceManager.GetString("Label_PurviewNMJAJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料權限名稱(韓) 的當地語系化字串。
        /// </summary>
        internal static string Label_PurviewNMKOKR {
            get {
                return ResourceManager.GetString("Label_PurviewNMKOKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料權限名稱(泰) 的當地語系化字串。
        /// </summary>
        internal static string Label_PurviewNMTHTH {
            get {
                return ResourceManager.GetString("Label_PurviewNMTHTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料權限名稱(簡) 的當地語系化字串。
        /// </summary>
        internal static string Label_PurviewNMZHCN {
            get {
                return ResourceManager.GetString("Label_PurviewNMZHCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料權限名稱(繁) 的當地語系化字串。
        /// </summary>
        internal static string Label_PurviewNMZHTW {
            get {
                return ResourceManager.GetString("Label_PurviewNMZHTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備註 的當地語系化字串。
        /// </summary>
        internal static string Label_Remark {
            get {
                return ResourceManager.GetString("Label_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序 的當地語系化字串。
        /// </summary>
        internal static string Label_SortOrder {
            get {
                return ResourceManager.GetString("Label_SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_SysID {
            get {
                return ResourceManager.GetString("Label_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料權限明細已存在 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_IsExistSystemPurviewDetail {
            get {
                return ResourceManager.GetString("SystemMsg_IsExistSystemPurviewDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得資料權限明細列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_UnGetSystemPurviewDetail {
            get {
                return ResourceManager.GetString("SystemMsg_UnGetSystemPurviewDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得應用系統選單 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_UnGetUserSystemByIdList {
            get {
                return ResourceManager.GetString("SystemMsg_UnGetUserSystemByIdList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料權限明細 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemPurviewDetail {
            get {
                return ResourceManager.GetString("TabText_SystemPurviewDetail", resourceCulture);
            }
        }
    }
}
