//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysSystemEventTargetEDI {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysSystemEventTargetEDI() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysSystemEventTargetEDI", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 參數 的當地語系化字串。
        /// </summary>
        internal static string Button_EventPara {
            get {
                return ResourceManager.GetString("Button_EventPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增事件訂閱失敗 的當地語系化字串。
        /// </summary>
        internal static string InsertSubscriptiont_Failure {
            get {
                return ResourceManager.GetString("InsertSubscriptiont_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始日期 的當地語系化字串。
        /// </summary>
        internal static string Label_DTBegin {
            get {
                return ResourceManager.GetString("Label_DTBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結束日期 的當地語系化字串。
        /// </summary>
        internal static string Label_DTEnd {
            get {
                return ResourceManager.GetString("Label_DTEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 事件群組 的當地語系化字串。
        /// </summary>
        internal static string Label_EventGroupID {
            get {
                return ResourceManager.GetString("Label_EventGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 事件名稱 的當地語系化字串。
        /// </summary>
        internal static string Label_EventID {
            get {
                return ResourceManager.GetString("Label_EventID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 只查失敗結果資料 的當地語系化字串。
        /// </summary>
        internal static string Label_IsOnlyFail {
            get {
                return ResourceManager.GetString("Label_IsOnlyFail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_SysID {
            get {
                return ResourceManager.GetString("Label_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訂閱系統 的當地語系化字串。
        /// </summary>
        internal static string Label_TargetSysID {
            get {
                return ResourceManager.GetString("Label_TargetSysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認要執行重送動作嗎? 的當地語系化字串。
        /// </summary>
        internal static string SysMsg_Resend {
            get {
                return ResourceManager.GetString("SysMsg_Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 確認是否為IT管理者失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_CheckIsITManager_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_CheckIsITManager_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得事件主鍵名稱 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_UnGetSysSystemEventFullName {
            get {
                return ResourceManager.GetString("SystemMsg_UnGetSysSystemEventFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得應用系統選單 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_UnGetSystemByIdList {
            get {
                return ResourceManager.GetString("SystemMsg_UnGetSystemByIdList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得事件記錄清單列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_UnGetSystemEventTargetEDIList {
            get {
                return ResourceManager.GetString("SystemMsg_UnGetSystemEventTargetEDIList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 明細 的當地語系化字串。
        /// </summary>
        internal static string Table_Detail {
            get {
                return ResourceManager.GetString("Table_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 事件參數 的當地語系化字串。
        /// </summary>
        internal static string Table_EventPara {
            get {
                return ResourceManager.GetString("Table_EventPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 執行事件序號 的當地語系化字串。
        /// </summary>
        internal static string Table_ExecEDIEventNo {
            get {
                return ResourceManager.GetString("Table_ExecEDIEventNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增作業日期 的當地語系化字串。
        /// </summary>
        internal static string Table_InsertEDIDate {
            get {
                return ResourceManager.GetString("Table_InsertEDIDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增作業序號 的當地語系化字串。
        /// </summary>
        internal static string Table_InsertEDINo {
            get {
                return ResourceManager.GetString("Table_InsertEDINo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增作業時間 的當地語系化字串。
        /// </summary>
        internal static string Table_InsertEDITime {
            get {
                return ResourceManager.GetString("Table_InsertEDITime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 重送 的當地語系化字串。
        /// </summary>
        internal static string Table_Resend {
            get {
                return ResourceManager.GetString("Table_Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結果 的當地語系化字串。
        /// </summary>
        internal static string Table_ResultNM {
            get {
                return ResourceManager.GetString("Table_ResultNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 指定重送 的當地語系化字串。
        /// </summary>
        internal static string Table_SpecifyResend {
            get {
                return ResourceManager.GetString("Table_SpecifyResend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 狀態 的當地語系化字串。
        /// </summary>
        internal static string Table_StatusNM {
            get {
                return ResourceManager.GetString("Table_StatusNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始同步時間 的當地語系化字串。
        /// </summary>
        internal static string Table_TargetDTBegin {
            get {
                return ResourceManager.GetString("Table_TargetDTBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結束同步時間 的當地語系化字串。
        /// </summary>
        internal static string Table_TargetDTEnd {
            get {
                return ResourceManager.GetString("Table_TargetDTEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 同步結果 的當地語系化字串。
        /// </summary>
        internal static string Table_TargetResultNM {
            get {
                return ResourceManager.GetString("Table_TargetResultNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 回傳API作業序號 的當地語系化字串。
        /// </summary>
        internal static string Table_TargetReturnAPINo {
            get {
                return ResourceManager.GetString("Table_TargetReturnAPINo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 同步狀態 的當地語系化字串。
        /// </summary>
        internal static string Table_TargetStatusNM {
            get {
                return ResourceManager.GetString("Table_TargetStatusNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 訂閱系統 的當地語系化字串。
        /// </summary>
        internal static string Table_TargetSysNM {
            get {
                return ResourceManager.GetString("Table_TargetSysNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 事件紀錄清單 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemEventTargetEDI {
            get {
                return ResourceManager.GetString("TabText_SystemEventTargetEDI", resourceCulture);
            }
        }
    }
}
