//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysSystemFunElmUser {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysSystemFunElmUser() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysSystemFunElmUser", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 確定 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_Confirm {
            get {
                return ResourceManager.GetString("JsMsg_Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得使用者資訊失敗 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_GetFunElmUserInfo_Failure {
            get {
                return ResourceManager.GetString("JsMsg_GetFunElmUserInfo_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 輸入人員已重複 或 無此員工編號，請重新檢查 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_NotHaveUserIDOrRepeat_Failure {
            get {
                return ResourceManager.GetString("JsMsg_NotHaveUserIDOrRepeat_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能元素使用者設定 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_SetElmUser {
            get {
                return ResourceManager.GetString("JsMsg_SetElmUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 已重複 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_UserIDRepaet_Failure {
            get {
                return ResourceManager.GetString("JsMsg_UserIDRepaet_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入正確使用者格式 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_UserMemoFormate_Error {
            get {
                return ResourceManager.GetString("JsMsg_UserMemoFormate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增方式 的當地語系化字串。
        /// </summary>
        internal static string Label_AddType {
            get {
                return ResourceManager.GetString("Label_AddType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示 的當地語系化字串。
        /// </summary>
        internal static string Label_Display {
            get {
                return ResourceManager.GetString("Label_Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預設顯示狀態 的當地語系化字串。
        /// </summary>
        internal static string Label_DisplaySts {
            get {
                return ResourceManager.GetString("Label_DisplaySts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ERP-簽核單 的當地語系化字串。
        /// </summary>
        internal static string Label_ErpSign {
            get {
                return ResourceManager.GetString("Label_ErpSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能代碼 的當地語系化字串。
        /// </summary>
        internal static string Label_FunActionName {
            get {
                return ResourceManager.GetString("Label_FunActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能群組 的當地語系化字串。
        /// </summary>
        internal static string Label_FunControllerID {
            get {
                return ResourceManager.GetString("Label_FunControllerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 元素名稱 的當地語系化字串。
        /// </summary>
        internal static string Label_FunElmNM {
            get {
                return ResourceManager.GetString("Label_FunElmNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 隱藏 的當地語系化字串。
        /// </summary>
        internal static string Label_Hide {
            get {
                return ResourceManager.GetString("Label_Hide", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 遮罩 的當地語系化字串。
        /// </summary>
        internal static string Label_Masking {
            get {
                return ResourceManager.GetString("Label_Masking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改紀錄 的當地語系化字串。
        /// </summary>
        internal static string Label_ModifyRecord {
            get {
                return ResourceManager.GetString("Label_ModifyRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 多人 的當地語系化字串。
        /// </summary>
        internal static string Label_MultiUser {
            get {
                return ResourceManager.GetString("Label_MultiUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 唯讀 的當地語系化字串。
        /// </summary>
        internal static string Label_ReadOnly {
            get {
                return ResourceManager.GetString("Label_ReadOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 單人 的當地語系化字串。
        /// </summary>
        internal static string Label_SingleUser {
            get {
                return ResourceManager.GetString("Label_SingleUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能元素使用者設定 的當地語系化字串。
        /// </summary>
        internal static string Label_SystemFunElmAddUser {
            get {
                return ResourceManager.GetString("Label_SystemFunElmAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者 的當地語系化字串。
        /// </summary>
        internal static string Label_User {
            get {
                return ResourceManager.GetString("Label_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯功能元素使用者失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_EditElmAuthUser_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_EditElmAuthUser_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得功能元素使用者明細失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetElmAuthUserDetail_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_GetElmAuthUserDetail_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 紀錄功能元素使用者明細失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_RecordLogSystemUserFunElm_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_RecordLogSystemUserFunElm_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 儲存成功 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_Save_Success {
            get {
                return ResourceManager.GetString("SystemMsg_Save_Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 員編重複 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_UserIDRepeat_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_UserIDRepeat_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入正確使用者格式 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_UserMemoFormate_Error {
            get {
                return ResourceManager.GetString("SystemMsg_UserMemoFormate_Error", resourceCulture);
            }
        }
    }
}
