//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別為自動產生，方法是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysSystemWorkFlowSignatureDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysSystemWorkFlowSignatureDetail() {
        }
        
        /// <summary>
        ///   傳回這個類別所使用的快取 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysSystemWorkFlowSignatureDetail", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除工作流程簽核明細失敗 的當地語系化字串。
        /// </summary>
        internal static string DeleteWFSignatureDetail_Failure {
            get {
                return ResourceManager.GetString("DeleteWFSignatureDetail_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該簽核設計已被使用於流程中，不能刪除 的當地語系化字串。
        /// </summary>
        internal static string DeleteWFSignatureDetail_RuntimeExist {
            get {
                return ResourceManager.GetString("DeleteWFSignatureDetail_RuntimeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯工作流程簽核明細失敗 的當地語系化字串。
        /// </summary>
        internal static string EditWFSignatureDetail_Failure {
            get {
                return ResourceManager.GetString("EditWFSignatureDetail_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統角色：必須選取 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_SystemRoleIsEmpty {
            get {
                return ResourceManager.GetString("JsMsg_SystemRoleIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ＊API參數：?ClientSysID=&amp;APIPara={&quot;WFNo&quot;:&quot;&quot;,&quot;NodeNo&quot;:&quot;&quot;,&quot;UserID&quot;:&quot;&quot;,&quot;SysID&quot;:&quot;&quot;,&quot;FlowID&quot;:&quot;&quot;,&quot;FlowVer&quot;:&quot;&quot;,&quot;NodeID&quot;:&quot;&quot;,&quot;SigSeq&quot;:&quot;&quot;}&lt;br /&gt;
        ///　回傳結果：{&quot;UserIDList&quot;:[&quot;&quot;]} 的當地語系化字串。
        /// </summary>
        internal static string Label_APIMemo {
            get {
                return ResourceManager.GetString("Label_APIMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ＊API參數：?ClientSysID=&amp;APIPara={&quot;WFNo&quot;:&quot;&quot;,&quot;NodeNo&quot;:&quot;&quot;,&quot;UserID&quot;:&quot;&quot;,&quot;SysID&quot;:&quot;&quot;,&quot;FlowID&quot;:&quot;&quot;,&quot;FlowVer&quot;:&quot;&quot;,&quot;NodeID&quot;:&quot;&quot;,&quot;SigSeq&quot;:&quot;&quot;}&lt;br /&gt;
        ///　回傳結果：{&quot;Result&quot;:&quot;&quot;, &quot;Message&quot;:&quot;&quot;} Result=Y/N 的當地語系化字串。
        /// </summary>
        internal static string Label_CheckMemo {
            get {
                return ResourceManager.GetString("Label_CheckMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 驗證功能名稱 的當地語系化字串。
        /// </summary>
        internal static string Label_ChkFunActionName {
            get {
                return ResourceManager.GetString("Label_ChkFunActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 驗證功能群組 的當地語系化字串。
        /// </summary>
        internal static string Label_ChkFunControllerID {
            get {
                return ResourceManager.GetString("Label_ChkFunControllerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 驗證功能應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_ChkFunSysID {
            get {
                return ResourceManager.GetString("Label_ChkFunSysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 API自訂功能名稱 的當地語系化字串。
        /// </summary>
        internal static string Label_FunActionName {
            get {
                return ResourceManager.GetString("Label_FunActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 API自訂功能群組 的當地語系化字串。
        /// </summary>
        internal static string Label_FunControllerID {
            get {
                return ResourceManager.GetString("Label_FunControllerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 API自訂功能應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_FunSysID {
            get {
                return ResourceManager.GetString("Label_FunSysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否為必要簽核 的當地語系化字串。
        /// </summary>
        internal static string Label_IsReq {
            get {
                return ResourceManager.GetString("Label_IsReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備註 的當地語系化字串。
        /// </summary>
        internal static string Label_Remark {
            get {
                return ResourceManager.GetString("Label_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色 的當地語系化字串。
        /// </summary>
        internal static string Label_Role {
            get {
                return ResourceManager.GetString("Label_Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 前簽核點 的當地語系化字串。
        /// </summary>
        internal static string Label_SigSeq {
            get {
                return ResourceManager.GetString("Label_SigSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 簽核關卡 的當地語系化字串。
        /// </summary>
        internal static string Label_SigStep {
            get {
                return ResourceManager.GetString("Label_SigStep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 簽核人員類型 的當地語系化字串。
        /// </summary>
        internal static string Label_SigType {
            get {
                return ResourceManager.GetString("Label_SigType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_SysID {
            get {
                return ResourceManager.GetString("Label_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ＊若要由流程建立者「自行輸入」簽核人員，請不要點選任何前簽核點、API功能資料、及角色；&lt;br /&gt;
        ///　若要「與前簽核點相同」簽核人員（例如驗收節點），請輸入前簽核點；&lt;br /&gt;
        ///　若要由「系統使用API自訂」簽核人員，請設定API功能資料；&lt;br /&gt;
        ///　若要使用「預設權限簽核表」代入簽核人員，請勾選USER角色；&lt;br /&gt;
        ///　若勾選任一角色，代表簽核人員為符合該角色的「角色使用者下拉選單」，由流程建立者自行選取。 的當地語系化字串。
        /// </summary>
        internal static string Label_SystemRoleMemo {
            get {
                return ResourceManager.GetString("Label_SystemRoleMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程 的當地語系化字串。
        /// </summary>
        internal static string Label_WFFlow {
            get {
                return ResourceManager.GetString("Label_WFFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程版本 的當地語系化字串。
        /// </summary>
        internal static string Label_WFFlowVer {
            get {
                return ResourceManager.GetString("Label_WFFlowVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程節點 的當地語系化字串。
        /// </summary>
        internal static string Label_WFNode {
            get {
                return ResourceManager.GetString("Label_WFNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 簽核點序號 的當地語系化字串。
        /// </summary>
        internal static string Label_WFSigSeq {
            get {
                return ResourceManager.GetString("Label_WFSigSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 簽核點名稱(英) 的當地語系化字串。
        /// </summary>
        internal static string Label_WFSigSeqENUS {
            get {
                return ResourceManager.GetString("Label_WFSigSeqENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 簽核點名稱(日) 的當地語系化字串。
        /// </summary>
        internal static string Label_WFSigSeqJAJP {
            get {
                return ResourceManager.GetString("Label_WFSigSeqJAJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 簽核點名稱(韓) 的當地語系化字串。
        /// </summary>
        internal static string Label_WFSigSeqKOKR {
            get {
                return ResourceManager.GetString("Label_WFSigSeqKOKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 簽核點名稱(泰) 的當地語系化字串。
        /// </summary>
        internal static string Label_WFSigSeqTHTH {
            get {
                return ResourceManager.GetString("Label_WFSigSeqTHTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 簽核點名稱(簡) 的當地語系化字串。
        /// </summary>
        internal static string Label_WFSigSeqZHCN {
            get {
                return ResourceManager.GetString("Label_WFSigSeqZHCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 簽核點名稱(繁) 的當地語系化字串。
        /// </summary>
        internal static string Label_WFSigSeqZHTW {
            get {
                return ResourceManager.GetString("Label_WFSigSeqZHTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程簽核明細已存在 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_AddWFSignatureDetailExist {
            get {
                return ResourceManager.GetString("SystemMsg_AddWFSignatureDetailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得API功能列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemAPIFuntionList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemAPIFuntionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得API群組列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemAPIGroupList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemAPIGroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得系統角色列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemRoleIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemRoleIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得工作流程節點檔失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemWFNode {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemWFNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得工作流程列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemWorkFlowIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemWorkFlowIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得工作流程節點列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemWorkFlowNodeIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemWorkFlowNodeIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得應用系統列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSystemSysIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSystemSysIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得工作流程簽核清單明細列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSystemWorkFlowSignatureDetail {
            get {
                return ResourceManager.GetString("SystemMsg_GetSystemWorkFlowSignatureDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得員工應用系統列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysUserSystemSysIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysUserSystemSysIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得工作流程列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysUserSystemWorkFlowIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysUserSystemWorkFlowIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您不具有使用此應用系統的權限 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_SetHasSysID {
            get {
                return ResourceManager.GetString("SystemMsg_SetHasSysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程簽核明細 的當地語系化字串。
        /// </summary>
        internal static string TabText_WFSignatureDetail {
            get {
                return ResourceManager.GetString("TabText_WFSignatureDetail", resourceCulture);
            }
        }
    }
}
