//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysSystemRoleCondition {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysSystemRoleCondition() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysSystemRoleCondition", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 取得系統角色預設條件清單失敗 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_GetSysSystemRoleConditionList_Failure {
            get {
                return ResourceManager.GetString("JsMsg_GetSysSystemRoleConditionList_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得應用系統角色清單失敗 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_GetSysSystemRoleIDList_Failure {
            get {
                return ResourceManager.GetString("JsMsg_GetSysSystemRoleIDList_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 條件代碼 的當地語系化字串。
        /// </summary>
        internal static string Label_ConditionCode {
            get {
                return ResourceManager.GetString("Label_ConditionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 包含角色 的當地語系化字串。
        /// </summary>
        internal static string Label_ContainRole {
            get {
                return ResourceManager.GetString("Label_ContainRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序 的當地語系化字串。
        /// </summary>
        internal static string Label_Sequence {
            get {
                return ResourceManager.GetString("Label_Sequence", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_SysID {
            get {
                return ResourceManager.GetString("Label_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得系統角條件代碼失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemConditionIDList_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemConditionIDList_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得系統角色預設條件失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemRoleConditionList_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemRoleConditionList_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得應用系統列表失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysUserSystemSysIDList_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysUserSystemSysIDList_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 條件代碼 的當地語系化字串。
        /// </summary>
        internal static string Table_ConditionID {
            get {
                return ResourceManager.GetString("Table_ConditionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 條件名稱 的當地語系化字串。
        /// </summary>
        internal static string Table_ConditionNM {
            get {
                return ResourceManager.GetString("Table_ConditionNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 明細 的當地語系化字串。
        /// </summary>
        internal static string Table_Detail {
            get {
                return ResourceManager.GetString("Table_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備註 的當地語系化字串。
        /// </summary>
        internal static string Table_Remark {
            get {
                return ResourceManager.GetString("Table_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色名單 的當地語系化字串。
        /// </summary>
        internal static string Table_RoleNM {
            get {
                return ResourceManager.GetString("Table_RoleNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序 的當地語系化字串。
        /// </summary>
        internal static string Table_SortOrder {
            get {
                return ResourceManager.GetString("Table_SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新時間 的當地語系化字串。
        /// </summary>
        internal static string Table_UpdDT {
            get {
                return ResourceManager.GetString("Table_UpdDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新人員 的當地語系化字串。
        /// </summary>
        internal static string Table_UpdUserNM {
            get {
                return ResourceManager.GetString("Table_UpdUserNM", resourceCulture);
            }
        }
    }
}
