//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別為自動產生，方法是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysSystemRoleConditionDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysSystemRoleConditionDetail() {
        }
        
        /// <summary>
        ///   傳回這個類別所使用的快取 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysSystemRoleConditionDetail", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 角色至少需勾選一項 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_IsValidSysRoleRequired_Failure {
            get {
                return ResourceManager.GetString("JsMsg_IsValidSysRoleRequired_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統角色預設權限規則至少一筆 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_IsValidSysRoleRulesRequired_Failure {
            get {
                return ResourceManager.GetString("JsMsg_IsValidSysRoleRulesRequired_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 依據條件 的當地語系化字串。
        /// </summary>
        internal static string Label_AccordingCondition {
            get {
                return ResourceManager.GetString("Label_AccordingCondition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增群組 的當地語系化字串。
        /// </summary>
        internal static string Label_AddGroup {
            get {
                return ResourceManager.GetString("Label_AddGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增規則 的當地語系化字串。
        /// </summary>
        internal static string Label_AddRule {
            get {
                return ResourceManager.GetString("Label_AddRule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 條件 的當地語系化字串。
        /// </summary>
        internal static string Label_Condition {
            get {
                return ResourceManager.GetString("Label_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 條件代碼 的當地語系化字串。
        /// </summary>
        internal static string Label_ConditionCode {
            get {
                return ResourceManager.GetString("Label_ConditionCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 條件名稱(英) 的當地語系化字串。
        /// </summary>
        internal static string Label_ConditionNMENUS {
            get {
                return ResourceManager.GetString("Label_ConditionNMENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 條件名稱(日) 的當地語系化字串。
        /// </summary>
        internal static string Label_ConditionNMJAJP {
            get {
                return ResourceManager.GetString("Label_ConditionNMJAJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 條件名稱(韓) 的當地語系化字串。
        /// </summary>
        internal static string Label_ConditionNMKOKR {
            get {
                return ResourceManager.GetString("Label_ConditionNMKOKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 條件名稱(泰) 的當地語系化字串。
        /// </summary>
        internal static string Label_ConditionNMTHTH {
            get {
                return ResourceManager.GetString("Label_ConditionNMTHTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 條件名稱(簡) 的當地語系化字串。
        /// </summary>
        internal static string Label_ConditionNMZHCN {
            get {
                return ResourceManager.GetString("Label_ConditionNMZHCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 條件名稱(繁) 的當地語系化字串。
        /// </summary>
        internal static string Label_ConditionNMZHTW {
            get {
                return ResourceManager.GetString("Label_ConditionNMZHTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預設 的當地語系化字串。
        /// </summary>
        internal static string Label_Default {
            get {
                return ResourceManager.GetString("Label_Default", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備註 的當地語系化字串。
        /// </summary>
        internal static string Label_Remark {
            get {
                return ResourceManager.GetString("Label_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色 的當地語系化字串。
        /// </summary>
        internal static string Label_Roles {
            get {
                return ResourceManager.GetString("Label_Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序 的當地語系化字串。
        /// </summary>
        internal static string Label_SortOrder {
            get {
                return ResourceManager.GetString("Label_SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_SysID {
            get {
                return ResourceManager.GetString("Label_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 紀錄系統角色預設條件明細失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_AddSystemRoleConditionLogData_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_AddSystemRoleConditionLogData_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除系統角色預設條件明細失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_DeleteSystemRoleCondition_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_DeleteSystemRoleCondition_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯系統角色預設條件明細失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_EditSystemRoleCondition_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_EditSystemRoleCondition_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得應用系統名稱失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysNM_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysNM_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得系統角色預設條件明細失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemRoleConditionDetail_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemRoleConditionDetail_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得應用系統角色清單失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemRoleIDList_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemRoleIDList_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色至少需勾選一項 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_IsValidSysRoleRequired_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_IsValidSysRoleRequired_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統角色預設權限規則至少一筆 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_IsValidSysRoleRulesRequired_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_IsValidSysRoleRulesRequired_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統角色預設條件Json資料初始化失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_SetSystemRoleConditionFilterJsonString_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_SetSystemRoleConditionFilterJsonString_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統角色預設條件明細 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemRoleConditionDetail {
            get {
                return ResourceManager.GetString("TabText_SystemRoleConditionDetail", resourceCulture);
            }
        }
    }
}
