//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別為自動產生，方法是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysSystemFunElmDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysSystemFunElmDetail() {
        }
        
        /// <summary>
        ///   傳回這個類別所使用的快取 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysSystemFunElmDetail", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇預設顯示狀態 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_FunElmDisplayDefaultType_Required {
            get {
                return ResourceManager.GetString("JsMsg_FunElmDisplayDefaultType_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 停用 的當地語系化字串。
        /// </summary>
        internal static string Label_Disable {
            get {
                return ResourceManager.GetString("Label_Disable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示狀態 的當地語系化字串。
        /// </summary>
        internal static string Label_DisplaySts {
            get {
                return ResourceManager.GetString("Label_DisplaySts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能代碼 的當地語系化字串。
        /// </summary>
        internal static string Label_FunActionName {
            get {
                return ResourceManager.GetString("Label_FunActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能群組 的當地語系化字串。
        /// </summary>
        internal static string Label_FunControllerID {
            get {
                return ResourceManager.GetString("Label_FunControllerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預設顯示狀態 的當地語系化字串。
        /// </summary>
        internal static string Label_FunElmDisplayDefaultType {
            get {
                return ResourceManager.GetString("Label_FunElmDisplayDefaultType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能元素代碼 的當地語系化字串。
        /// </summary>
        internal static string Label_FunElmID {
            get {
                return ResourceManager.GetString("Label_FunElmID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能元素名稱(英) 的當地語系化字串。
        /// </summary>
        internal static string Label_FunElmNMENUS {
            get {
                return ResourceManager.GetString("Label_FunElmNMENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能元素名稱(日) 的當地語系化字串。
        /// </summary>
        internal static string Label_FunElmNMJAJP {
            get {
                return ResourceManager.GetString("Label_FunElmNMJAJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能元素名稱(韓) 的當地語系化字串。
        /// </summary>
        internal static string Label_FunElmNMKOKR {
            get {
                return ResourceManager.GetString("Label_FunElmNMKOKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能元素名稱(泰) 的當地語系化字串。
        /// </summary>
        internal static string Label_FunElmNMTHTH {
            get {
                return ResourceManager.GetString("Label_FunElmNMTHTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能元素名稱(簡) 的當地語系化字串。
        /// </summary>
        internal static string Label_FunElmNMZHCN {
            get {
                return ResourceManager.GetString("Label_FunElmNMZHCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能元素名稱(繁) 的當地語系化字串。
        /// </summary>
        internal static string Label_FunElmNMZHTW {
            get {
                return ResourceManager.GetString("Label_FunElmNMZHTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_SysID {
            get {
                return ResourceManager.GetString("Label_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能元素明細 的當地語系化字串。
        /// </summary>
        internal static string Label_SystemFunElmDetail {
            get {
                return ResourceManager.GetString("Label_SystemFunElmDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者 的當地語系化字串。
        /// </summary>
        internal static string Label_User {
            get {
                return ResourceManager.GetString("Label_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除功能元素明細失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_DeleteSystemFunElmDetail_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_DeleteSystemFunElmDetail_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯功能元素明細失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_EditSystemFunElmDetail_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_EditSystemFunElmDetail_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇功能群組及功能代碼 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_FunControllerAndFunAction_Required {
            get {
                return ResourceManager.GetString("SystemMsg_FunControllerAndFunAction_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得功能元素明細失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSystemFunElmDetail_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_GetSystemFunElmDetail_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得系統資訊清單失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSystemInfoList_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_GetSystemInfoList_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 紀錄功能元素明細失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_RecordLogSysSystemFunElm_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_RecordLogSysSystemFunElm_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能元素代碼重複 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_SystemFunElmIDRepeat {
            get {
                return ResourceManager.GetString("SystemMsg_SystemFunElmIDRepeat", resourceCulture);
            }
        }
    }
}
