//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別為自動產生，方法是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysSystemEventDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysSystemEventDetail() {
        }
        
        /// <summary>
        ///   傳回這個類別所使用的快取 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysSystemEventDetail", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除事件訂閱明細失敗&lt;br /&gt;尚有：{0} 使用此項設定 的當地語系化字串。
        /// </summary>
        internal static string DeleteSystemEventDetailResult_DataExist {
            get {
                return ResourceManager.GetString("DeleteSystemEventDetailResult_DataExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除事件訂閱明細失敗 的當地語系化字串。
        /// </summary>
        internal static string DeleteSystemEventDetailResult_Failure {
            get {
                return ResourceManager.GetString("DeleteSystemEventDetailResult_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯事件訂閱明細失敗 的當地語系化字串。
        /// </summary>
        internal static string EditSystemEventDetailResult_Failure {
            get {
                return ResourceManager.GetString("EditSystemEventDetailResult_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ＊新增事件訂閱需至「系統管理」→「API清單」→「雄獅ERP平台 (ERPAP)」→「電子資料交換服務 (EDIService)」→「事件訂閱委派中心 (Distributor)」→「授權」設定API權限 的當地語系化字串。
        /// </summary>
        internal static string Label_APIDescription {
            get {
                return ResourceManager.GetString("Label_APIDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 事件群組 的當地語系化字串。
        /// </summary>
        internal static string Label_EventGroupID {
            get {
                return ResourceManager.GetString("Label_EventGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 事件代碼 的當地語系化字串。
        /// </summary>
        internal static string Label_EventID {
            get {
                return ResourceManager.GetString("Label_EventID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 事件名稱(英) 的當地語系化字串。
        /// </summary>
        internal static string Label_EventNMENUS {
            get {
                return ResourceManager.GetString("Label_EventNMENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 事件名稱(日) 的當地語系化字串。
        /// </summary>
        internal static string Label_EventNMJAJP {
            get {
                return ResourceManager.GetString("Label_EventNMJAJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 事件名稱(韓) 的當地語系化字串。
        /// </summary>
        internal static string Label_EventNMKOKR {
            get {
                return ResourceManager.GetString("Label_EventNMKOKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 事件名稱(泰) 的當地語系化字串。
        /// </summary>
        internal static string Label_EventNMTHTH {
            get {
                return ResourceManager.GetString("Label_EventNMTHTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 事件名稱(簡) 的當地語系化字串。
        /// </summary>
        internal static string Label_EventNMZHCN {
            get {
                return ResourceManager.GetString("Label_EventNMZHCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 事件名稱(繁) 的當地語系化字串。
        /// </summary>
        internal static string Label_EventNMZHTW {
            get {
                return ResourceManager.GetString("Label_EventNMZHTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 事件參數 的當地語系化字串。
        /// </summary>
        internal static string Label_EventPara {
            get {
                return ResourceManager.GetString("Label_EventPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 事件訂閱清單 的當地語系化字串。
        /// </summary>
        internal static string Label_EventTarget {
            get {
                return ResourceManager.GetString("Label_EventTarget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否停用 的當地語系化字串。
        /// </summary>
        internal static string Label_IsDisable {
            get {
                return ResourceManager.GetString("Label_IsDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備註 的當地語系化字串。
        /// </summary>
        internal static string Label_Remark {
            get {
                return ResourceManager.GetString("Label_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序 的當地語系化字串。
        /// </summary>
        internal static string Label_SortOrder {
            get {
                return ResourceManager.GetString("Label_SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_SysID {
            get {
                return ResourceManager.GetString("Label_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您不具有使用此應用系統的權限 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_HasNotSysID {
            get {
                return ResourceManager.GetString("SystemMsg_HasNotSysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 事件訂閱明細已存在 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_IsExistSystemEventDetail {
            get {
                return ResourceManager.GetString("SystemMsg_IsExistSystemEventDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得事件群組選單 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_UnGetSysSystemEventGroupByIdList {
            get {
                return ResourceManager.GetString("SystemMsg_UnGetSysSystemEventGroupByIdList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得事件訂閱明細列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_UnGetSystemEventDetail {
            get {
                return ResourceManager.GetString("SystemMsg_UnGetSystemEventDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得應用系統選單 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_UnGetUserSystemByIdList {
            get {
                return ResourceManager.GetString("SystemMsg_UnGetUserSystemByIdList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 事件訂閱明細 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemEventDetail {
            get {
                return ResourceManager.GetString("TabText_SystemEventDetail", resourceCulture);
            }
        }
    }
}
