//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysSystemRoleFunList {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysSystemRoleFunList() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysSystemRoleFunList", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得功能群組與功能名稱清單 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_GetSysControllerIDAndSysFunActionNMList_Failure {
            get {
                return ResourceManager.GetString("JsMsg_GetSysControllerIDAndSysFunActionNMList_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 第{0}筆,資料填寫不完整,功能名稱&amp;功能名稱必須輸入!!! 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_RequiredControllerActionNM {
            get {
                return ResourceManager.GetString("JsMsg_RequiredControllerActionNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 第 {0} 筆與第 {1} 筆為相同的!!! 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_TheSameData {
            get {
                return ResourceManager.GetString("JsMsg_TheSameData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能群組 的當地語系化字串。
        /// </summary>
        internal static string Label_FunGroup {
            get {
                return ResourceManager.GetString("Label_FunGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色名稱 的當地語系化字串。
        /// </summary>
        internal static string Label_RoleNM {
            get {
                return ResourceManager.GetString("Label_RoleNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統(子系統) 的當地語系化字串。
        /// </summary>
        internal static string Label_SubSysID {
            get {
                return ResourceManager.GetString("Label_SubSysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_SysID {
            get {
                return ResourceManager.GetString("Label_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯角色功能清單失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_EditSystemRoleFunList_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_EditSystemRoleFunList_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得功能群組與功能名稱清單 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysControllerIDAndSysFunActionNMList_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysControllerIDAndSysFunActionNMList_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得功能群組清單 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemFunControllerIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemFunControllerIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得系統使用者清單 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSystemRoleFunList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSystemRoleFunList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能名稱 的當地語系化字串。
        /// </summary>
        internal static string Table_FunNM {
            get {
                return ResourceManager.GetString("Table_FunNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新時間 的當地語系化字串。
        /// </summary>
        internal static string Table_UpdDT {
            get {
                return ResourceManager.GetString("Table_UpdDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新人員 的當地語系化字串。
        /// </summary>
        internal static string Table_UpdUserNM {
            get {
                return ResourceManager.GetString("Table_UpdUserNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色功能清單 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemRoleFunList {
            get {
                return ResourceManager.GetString("TabText_SystemRoleFunList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 明細 的當地語系化字串。
        /// </summary>
        internal static string Text_Detail {
            get {
                return ResourceManager.GetString("Text_Detail", resourceCulture);
            }
        }
    }
}
