//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別為自動產生，方法是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysSystemCultureSetting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysSystemCultureSetting() {
        }
        
        /// <summary>
        ///   傳回這個類別所使用的快取 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysSystemCultureSetting", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 發佈 的當地語系化字串。
        /// </summary>
        internal static string Button_Release {
            get {
                return ResourceManager.GetString("Button_Release", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 語系代碼 的當地語系化字串。
        /// </summary>
        internal static string Label_CultureID {
            get {
                return ResourceManager.GetString("Label_CultureID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 語系名稱 的當地語系化字串。
        /// </summary>
        internal static string Label_CultureNM {
            get {
                return ResourceManager.GetString("Label_CultureNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示名稱 的當地語系化字串。
        /// </summary>
        internal static string Label_DisplayNM {
            get {
                return ResourceManager.GetString("Label_DisplayNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 停用 的當地語系化字串。
        /// </summary>
        internal static string Label_IsDisable {
            get {
                return ResourceManager.GetString("Label_IsDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SERP使用 的當地語系化字串。
        /// </summary>
        internal static string Label_IsSerpUse {
            get {
                return ResourceManager.GetString("Label_IsSerpUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 語系代碼設定 的當地語系化字串。
        /// </summary>
        internal static string Label_SystemCultureSetting {
            get {
                return ResourceManager.GetString("Label_SystemCultureSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新時間 的當地語系化字串。
        /// </summary>
        internal static string Label_UpdDT {
            get {
                return ResourceManager.GetString("Label_UpdDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新人員 的當地語系化字串。
        /// </summary>
        internal static string Label_UpdUserNM {
            get {
                return ResourceManager.GetString("Label_UpdUserNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 發佈語系檔失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_UnGenerateCultureJsonFile {
            get {
                return ResourceManager.GetString("SystemMsg_UnGenerateCultureJsonFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得語系代碼選單 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_UnGetSystemCultureIDs {
            get {
                return ResourceManager.GetString("SystemMsg_UnGetSystemCultureIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得語系代碼清單列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_UnGetSystemCultures {
            get {
                return ResourceManager.GetString("SystemMsg_UnGetSystemCultures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 語系代碼 的當地語系化字串。
        /// </summary>
        internal static string Table_CultureID {
            get {
                return ResourceManager.GetString("Table_CultureID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 語系名稱 的當地語系化字串。
        /// </summary>
        internal static string Table_CultureNM {
            get {
                return ResourceManager.GetString("Table_CultureNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 顯示名稱 的當地語系化字串。
        /// </summary>
        internal static string Table_DisplayNM {
            get {
                return ResourceManager.GetString("Table_DisplayNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 停用 的當地語系化字串。
        /// </summary>
        internal static string Table_IsDisable {
            get {
                return ResourceManager.GetString("Table_IsDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SERP使用 的當地語系化字串。
        /// </summary>
        internal static string Table_IsSerpUse {
            get {
                return ResourceManager.GetString("Table_IsSerpUse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新時間 的當地語系化字串。
        /// </summary>
        internal static string Table_UpdDT {
            get {
                return ResourceManager.GetString("Table_UpdDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新人員 的當地語系化字串。
        /// </summary>
        internal static string Table_UpdUserNM {
            get {
                return ResourceManager.GetString("Table_UpdUserNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 明細 的當地語系化字串。
        /// </summary>
        internal static string Text_Detail {
            get {
                return ResourceManager.GetString("Text_Detail", resourceCulture);
            }
        }
    }
}
