//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysSystemAPIAuthorize {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysSystemAPIAuthorize() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysSystemAPIAuthorize", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 參數 的當地語系化字串。
        /// </summary>
        internal static string Button_APIPara {
            get {
                return ResourceManager.GetString("Button_APIPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除API授權失敗 的當地語系化字串。
        /// </summary>
        internal static string DeleteSystemAPIAuthorize_Failure {
            get {
                return ResourceManager.GetString("DeleteSystemAPIAuthorize_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 新增API授權失敗 的當地語系化字串。
        /// </summary>
        internal static string EditSystemAPIAuthorize_Failure {
            get {
                return ResourceManager.GetString("EditSystemAPIAuthorize_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 API功能 的當地語系化字串。
        /// </summary>
        internal static string Label_APIFunID {
            get {
                return ResourceManager.GetString("Label_APIFunID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 API群組 的當地語系化字串。
        /// </summary>
        internal static string Label_APIGroupID {
            get {
                return ResourceManager.GetString("Label_APIGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 API參數 的當地語系化字串。
        /// </summary>
        internal static string Label_APIPara {
            get {
                return ResourceManager.GetString("Label_APIPara", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 授權系統 的當地語系化字串。
        /// </summary>
        internal static string Label_ClientSysID {
            get {
                return ResourceManager.GetString("Label_ClientSysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除 的當地語系化字串。
        /// </summary>
        internal static string Label_Delete {
            get {
                return ResourceManager.GetString("Label_Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_SysID {
            get {
                return ResourceManager.GetString("Label_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新時間 的當地語系化字串。
        /// </summary>
        internal static string Label_UpdDT {
            get {
                return ResourceManager.GetString("Label_UpdDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新人員 的當地語系化字串。
        /// </summary>
        internal static string Label_UpdUserNM {
            get {
                return ResourceManager.GetString("Label_UpdUserNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得API主鍵名稱列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_UnGetSysSystemAPIFullName {
            get {
                return ResourceManager.GetString("SystemMsg_UnGetSysSystemAPIFullName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得API授權清單列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_UnGetSystemAPIAuthorizeList {
            get {
                return ResourceManager.GetString("SystemMsg_UnGetSystemAPIAuthorizeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得應用系統選單 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_UnGetSystemByIdList {
            get {
                return ResourceManager.GetString("SystemMsg_UnGetSystemByIdList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 API授權清單 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemAPIAuthorize {
            get {
                return ResourceManager.GetString("TabText_SystemAPIAuthorize", resourceCulture);
            }
        }
    }
}
