//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysSystemFunToolPara {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysSystemFunToolPara() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysSystemFunToolPara", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 功能名稱 的當地語系化字串。
        /// </summary>
        internal static string Label_FunActionName {
            get {
                return ResourceManager.GetString("Label_FunActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 群組功能 的當地語系化字串。
        /// </summary>
        internal static string Label_FunControllerID {
            get {
                return ResourceManager.GetString("Label_FunControllerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 參數代碼 的當地語系化字串。
        /// </summary>
        internal static string Label_ParaID {
            get {
                return ResourceManager.GetString("Label_ParaID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 參數值 的當地語系化字串。
        /// </summary>
        internal static string Label_ParaValue {
            get {
                return ResourceManager.GetString("Label_ParaValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_SysID {
            get {
                return ResourceManager.GetString("Label_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工具編號 的當地語系化字串。
        /// </summary>
        internal static string Label_ToolNo {
            get {
                return ResourceManager.GetString("Label_ToolNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工具名稱 的當地語系化字串。
        /// </summary>
        internal static string Label_TooNM {
            get {
                return ResourceManager.GetString("Label_TooNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否為當前使用 的當地語系化字串。
        /// </summary>
        internal static string Lable_IsCurrently {
            get {
                return ResourceManager.GetString("Lable_IsCurrently", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得系統功能條件參數表單失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSystemFunToolParaForm_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_GetSystemFunToolParaForm_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得系統功能條件參數表格失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSystemFunToolParaList_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_GetSystemFunToolParaList_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統功能條件參數 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemFunToolPara {
            get {
                return ResourceManager.GetString("TabText_SystemFunToolPara", resourceCulture);
            }
        }
    }
}
