//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別為自動產生，方法是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysSystemWorkFlowDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysSystemWorkFlowDetail() {
        }
        
        /// <summary>
        ///   傳回這個類別所使用的快取 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysSystemWorkFlowDetail", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 該流程尚有節點檔存在，不能刪除 的當地語系化字串。
        /// </summary>
        internal static string DeleteSystemWorkFlowDetailResult_ChildExist {
            get {
                return ResourceManager.GetString("DeleteSystemWorkFlowDetailResult_ChildExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除工作流程清單明細失敗 的當地語系化字串。
        /// </summary>
        internal static string DeleteSystemWorkFlowDetailResult_Failure {
            get {
                return ResourceManager.GetString("DeleteSystemWorkFlowDetailResult_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該流程已有紀錄檔存在，不能刪除 的當地語系化字串。
        /// </summary>
        internal static string DeleteSystemWorkFlowDetailResult_LogExist {
            get {
                return ResourceManager.GetString("DeleteSystemWorkFlowDetailResult_LogExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯工作流程清單明細失敗 的當地語系化字串。
        /// </summary>
        internal static string EditSystemWorkFlowDetailResult_Failure {
            get {
                return ResourceManager.GetString("EditSystemWorkFlowDetailResult_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 啟用日期或停用日期輸入錯誤 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_DateIsError {
            get {
                return ResourceManager.GetString("JsMsg_DateIsError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得API功能列表 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_GetSysSystemAPIFuns {
            get {
                return ResourceManager.GetString("JsMsg_GetSysSystemAPIFuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得API群組列表 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_GetSysSystemAPIGroups {
            get {
                return ResourceManager.GetString("JsMsg_GetSysSystemAPIGroups", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 自訂留言訊息功能欄位並未全部選取或並未全部欄位為空 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_SystemMsgFunctionIsNotFullyFilledOrNotEmpty {
            get {
                return ResourceManager.GetString("JsMsg_SystemMsgFunctionIsNotFullyFilledOrNotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統角色：必須選取 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_SystemRoleIsEmpty {
            get {
                return ResourceManager.GetString("JsMsg_SystemRoleIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 停用日期 的當地語系化字串。
        /// </summary>
        internal static string Label_DisableDate {
            get {
                return ResourceManager.GetString("Label_DisableDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 啟用日期 的當地語系化字串。
        /// </summary>
        internal static string Label_EnableDate {
            get {
                return ResourceManager.GetString("Label_EnableDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 流程管理使用者 的當地語系化字串。
        /// </summary>
        internal static string Label_FlowManUserID {
            get {
                return ResourceManager.GetString("Label_FlowManUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 流程類型 的當地語系化字串。
        /// </summary>
        internal static string Label_FlowType {
            get {
                return ResourceManager.GetString("Label_FlowType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否為起始畫面功能 的當地語系化字串。
        /// </summary>
        internal static string Label_IsStartFun {
            get {
                return ResourceManager.GetString("Label_IsStartFun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能名稱 的當地語系化字串。
        /// </summary>
        internal static string Label_MsgActionName {
            get {
                return ResourceManager.GetString("Label_MsgActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能群組 的當地語系化字串。
        /// </summary>
        internal static string Label_MsgControllerID {
            get {
                return ResourceManager.GetString("Label_MsgControllerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 自訂留言訊息功能 的當地語系化字串。
        /// </summary>
        internal static string Label_MsgFunActionName {
            get {
                return ResourceManager.GetString("Label_MsgFunActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_MsgSysID {
            get {
                return ResourceManager.GetString("Label_MsgSysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備註 的當地語系化字串。
        /// </summary>
        internal static string Label_Remark {
            get {
                return ResourceManager.GetString("Label_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序 的當地語系化字串。
        /// </summary>
        internal static string Label_SortOrder {
            get {
                return ResourceManager.GetString("Label_SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_SysID {
            get {
                return ResourceManager.GetString("Label_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ＊僅系統角色可建立此單 的當地語系化字串。
        /// </summary>
        internal static string Label_SysRoleMemo {
            get {
                return ResourceManager.GetString("Label_SysRoleMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統角色 的當地語系化字串。
        /// </summary>
        internal static string Label_SystemRole {
            get {
                return ResourceManager.GetString("Label_SystemRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 流程名稱(英) 的當地語系化字串。
        /// </summary>
        internal static string Label_WFFlowENUS {
            get {
                return ResourceManager.GetString("Label_WFFlowENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 流程名稱(日) 的當地語系化字串。
        /// </summary>
        internal static string Label_WFFlowJAJP {
            get {
                return ResourceManager.GetString("Label_WFFlowJAJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 流程名稱(韓) 的當地語系化字串。
        /// </summary>
        internal static string Label_WFFlowKOKR {
            get {
                return ResourceManager.GetString("Label_WFFlowKOKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 流程名稱(泰) 的當地語系化字串。
        /// </summary>
        internal static string Label_WFFlowTHTH {
            get {
                return ResourceManager.GetString("Label_WFFlowTHTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 流程名稱(簡) 的當地語系化字串。
        /// </summary>
        internal static string Label_WFFlowZHCN {
            get {
                return ResourceManager.GetString("Label_WFFlowZHCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 流程名稱(繁) 的當地語系化字串。
        /// </summary>
        internal static string Label_WFFlowZHTW {
            get {
                return ResourceManager.GetString("Label_WFFlowZHTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程群組 的當地語系化字串。
        /// </summary>
        internal static string Label_WorkFlowGroupID {
            get {
                return ResourceManager.GetString("Label_WorkFlowGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程 的當地語系化字串。
        /// </summary>
        internal static string Label_WorkFlowID {
            get {
                return ResourceManager.GetString("Label_WorkFlowID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 流程版本 的當地語系化字串。
        /// </summary>
        internal static string Label_WorkFlowVer {
            get {
                return ResourceManager.GetString("Label_WorkFlowVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程清單明細已存在 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_AddSystemWorkFlowDetailExist {
            get {
                return ResourceManager.GetString("SystemMsg_AddSystemWorkFlowDetailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得流程類型列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetFlowTypeList {
            get {
                return ResourceManager.GetString("SystemMsg_GetFlowTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得API功能列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemAPIFuntionList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemAPIFuntionList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得API群組列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemAPIGroupList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemAPIGroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得功能群組列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemFunControllerIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemFunControllerIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得功能名稱應用系統列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemFunNameList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemFunNameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得系統角色列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemRoleIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemRoleIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得工作流程群組列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemWorkFlowGroupIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemWorkFlowGroupIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得應用系統列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSystemSysIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSystemSysIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得工作流程清單明細列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSystemWorkFlowDetail {
            get {
                return ResourceManager.GetString("SystemMsg_GetSystemWorkFlowDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得員工應用系統列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysUserSystemSysIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysUserSystemSysIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您不具有使用此應用系統的權限 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_SetHasSysID {
            get {
                return ResourceManager.GetString("SystemMsg_SetHasSysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程明細 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemWorkFlowDetail {
            get {
                return ResourceManager.GetString("TabText_SystemWorkFlowDetail", resourceCulture);
            }
        }
    }
}
