//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysSystemWorkFlow {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysSystemWorkFlow() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysSystemWorkFlow", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 取得工作流程群組列表失敗 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_GetSysSystemWorkFlowGroupIDList {
            get {
                return ResourceManager.GetString("JsMsg_GetSysSystemWorkFlowGroupIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得工作流程節點列表失敗 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_GetSysSystemWorkFlowNodeIDList {
            get {
                return ResourceManager.GetString("JsMsg_GetSysSystemWorkFlowNodeIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得工作流程列表失敗 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_GetSysUserSystemWorkFlowIDList {
            get {
                return ResourceManager.GetString("JsMsg_GetSysUserSystemWorkFlowIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_SysID {
            get {
                return ResourceManager.GetString("Label_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程群組 的當地語系化字串。
        /// </summary>
        internal static string Label_WFFlowGroupID {
            get {
                return ResourceManager.GetString("Label_WFFlowGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程 的當地語系化字串。
        /// </summary>
        internal static string Label_WFFlowID {
            get {
                return ResourceManager.GetString("Label_WFFlowID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得工作流程群組列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemWorkFlowGroupIDListList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemWorkFlowGroupIDListList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得工作流程檔失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSystemWorkFlowList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSystemWorkFlowList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得員工應用系統列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysUserSystemSysIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysUserSystemSysIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得工作流程列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysUserSystemWorkFlowIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysUserSystemWorkFlowIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序儲存錯誤 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetWorkFlowSettingResult {
            get {
                return ResourceManager.GetString("SystemMsg_GetWorkFlowSettingResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 流程圖 的當地語系化字串。
        /// </summary>
        internal static string Table_Chart {
            get {
                return ResourceManager.GetString("Table_Chart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 明細 的當地語系化字串。
        /// </summary>
        internal static string Table_Detail {
            get {
                return ResourceManager.GetString("Table_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 停用日期 的當地語系化字串。
        /// </summary>
        internal static string Table_DisableDate {
            get {
                return ResourceManager.GetString("Table_DisableDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 啟用日期 的當地語系化字串。
        /// </summary>
        internal static string Table_EnableDate {
            get {
                return ResourceManager.GetString("Table_EnableDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程管理使用者 的當地語系化字串。
        /// </summary>
        internal static string Table_FlowManUserID {
            get {
                return ResourceManager.GetString("Table_FlowManUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程類型 的當地語系化字串。
        /// </summary>
        internal static string Table_FlowType {
            get {
                return ResourceManager.GetString("Table_FlowType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 節點檔 的當地語系化字串。
        /// </summary>
        internal static string Table_Node {
            get {
                return ResourceManager.GetString("Table_Node", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序 的當地語系化字串。
        /// </summary>
        internal static string Table_SortOrder {
            get {
                return ResourceManager.GetString("Table_SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Table_SysID {
            get {
                return ResourceManager.GetString("Table_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新時間 的當地語系化字串。
        /// </summary>
        internal static string Table_UpdDt {
            get {
                return ResourceManager.GetString("Table_UpdDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新人員 的當地語系化字串。
        /// </summary>
        internal static string Table_UpdUserNM {
            get {
                return ResourceManager.GetString("Table_UpdUserNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程群組 的當地語系化字串。
        /// </summary>
        internal static string Table_WFFlowGroupID {
            get {
                return ResourceManager.GetString("Table_WFFlowGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程 的當地語系化字串。
        /// </summary>
        internal static string Table_WFFlowID {
            get {
                return ResourceManager.GetString("Table_WFFlowID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程版本 的當地語系化字串。
        /// </summary>
        internal static string Table_WFFlowVer {
            get {
                return ResourceManager.GetString("Table_WFFlowVer", resourceCulture);
            }
        }
    }
}
