//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別為自動產生，方法是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysSystemWorkFlowGroupDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysSystemWorkFlowGroupDetail() {
        }
        
        /// <summary>
        ///   傳回這個類別所使用的快取 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysSystemWorkFlowGroupDetail", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除工作流程群組清單明細失敗，工作流程群組清單尚有資料使用此項設定 的當地語系化字串。
        /// </summary>
        internal static string DeleteSystemWorkFlowGroupDetailResult_DataExist {
            get {
                return ResourceManager.GetString("DeleteSystemWorkFlowGroupDetailResult_DataExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除工作流程群組清單明細失敗 的當地語系化字串。
        /// </summary>
        internal static string DeleteSystemWorkFlowGroupDetailResult_Failure {
            get {
                return ResourceManager.GetString("DeleteSystemWorkFlowGroupDetailResult_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯工作流程群組清單明細失敗 的當地語系化字串。
        /// </summary>
        internal static string EditSystemWorkFlowGroupDetailResult_Failure {
            get {
                return ResourceManager.GetString("EditSystemWorkFlowGroupDetailResult_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序 的當地語系化字串。
        /// </summary>
        internal static string Label_SortOrder {
            get {
                return ResourceManager.GetString("Label_SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_SysID {
            get {
                return ResourceManager.GetString("Label_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程群組名稱(英) 的當地語系化字串。
        /// </summary>
        internal static string Label_WFFlowGroupENUS {
            get {
                return ResourceManager.GetString("Label_WFFlowGroupENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程群組代碼 的當地語系化字串。
        /// </summary>
        internal static string Label_WFFlowGroupID {
            get {
                return ResourceManager.GetString("Label_WFFlowGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程群組名稱(日) 的當地語系化字串。
        /// </summary>
        internal static string Label_WFFlowGroupJAJP {
            get {
                return ResourceManager.GetString("Label_WFFlowGroupJAJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程群組名稱(韓) 的當地語系化字串。
        /// </summary>
        internal static string Label_WFFlowGroupKOKR {
            get {
                return ResourceManager.GetString("Label_WFFlowGroupKOKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程群組名稱(泰) 的當地語系化字串。
        /// </summary>
        internal static string Label_WFFlowGroupTHTH {
            get {
                return ResourceManager.GetString("Label_WFFlowGroupTHTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程群組名稱(簡) 的當地語系化字串。
        /// </summary>
        internal static string Label_WFFlowGroupZHCN {
            get {
                return ResourceManager.GetString("Label_WFFlowGroupZHCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程群組名稱(繁) 的當地語系化字串。
        /// </summary>
        internal static string Label_WFFlowGroupZHTW {
            get {
                return ResourceManager.GetString("Label_WFFlowGroupZHTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程群組清單明細已存在 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_AddSystemWorkFlowGroupDetailExist {
            get {
                return ResourceManager.GetString("SystemMsg_AddSystemWorkFlowGroupDetailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得應用系統列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSystemSysIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSystemSysIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得工作流程群組清單明細列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSystemWorkFlowGroupDetail {
            get {
                return ResourceManager.GetString("SystemMsg_GetSystemWorkFlowGroupDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得員工應用系統列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysUserSystemSysIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysUserSystemSysIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您不具有使用此應用系統的權限 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_SetHasSysID {
            get {
                return ResourceManager.GetString("SystemMsg_SetHasSysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程群組明細 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemWorkFlowGroupDetail {
            get {
                return ResourceManager.GetString("TabText_SystemWorkFlowGroupDetail", resourceCulture);
            }
        }
    }
}
