//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別為自動產生，方法是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysSystemWorkFlowDocumentDetail {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysSystemWorkFlowDocumentDetail() {
        }
        
        /// <summary>
        ///   傳回這個類別所使用的快取 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysSystemWorkFlowDocumentDetail", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 刪除工作流程文件明細失敗 的當地語系化字串。
        /// </summary>
        internal static string DeleteSysSystemWorkFlowDocumentDetail_Failure {
            get {
                return ResourceManager.GetString("DeleteSysSystemWorkFlowDocumentDetail_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 該文件設計已被使用於流程中，不能刪除 的當地語系化字串。
        /// </summary>
        internal static string DeleteSysSystemWorkFlowDocumentDetail_RuntimeExist {
            get {
                return ResourceManager.GetString("DeleteSysSystemWorkFlowDocumentDetail_RuntimeExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 編輯工作流程文件明細失敗 的當地語系化字串。
        /// </summary>
        internal static string EditSysSystemWorkFlowDocumentDetail_Failure {
            get {
                return ResourceManager.GetString("EditSysSystemWorkFlowDocumentDetail_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否為必要文件 的當地語系化字串。
        /// </summary>
        internal static string Label_IsReq {
            get {
                return ResourceManager.GetString("Label_IsReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備註 的當地語系化字串。
        /// </summary>
        internal static string Label_Remark {
            get {
                return ResourceManager.GetString("Label_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_SysID {
            get {
                return ResourceManager.GetString("Label_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 文件名稱(英) 的當地語系化字串。
        /// </summary>
        internal static string Label_WFDocENUS {
            get {
                return ResourceManager.GetString("Label_WFDocENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 文件名稱(日) 的當地語系化字串。
        /// </summary>
        internal static string Label_WFDocJAJP {
            get {
                return ResourceManager.GetString("Label_WFDocJAJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 文件名稱(韓) 的當地語系化字串。
        /// </summary>
        internal static string Label_WFDocKOKR {
            get {
                return ResourceManager.GetString("Label_WFDocKOKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 文件序號 的當地語系化字串。
        /// </summary>
        internal static string Label_WFDocSeq {
            get {
                return ResourceManager.GetString("Label_WFDocSeq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 文件名稱(泰) 的當地語系化字串。
        /// </summary>
        internal static string Label_WFDocTHTH {
            get {
                return ResourceManager.GetString("Label_WFDocTHTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 文件名稱(簡) 的當地語系化字串。
        /// </summary>
        internal static string Label_WFDocZHCN {
            get {
                return ResourceManager.GetString("Label_WFDocZHCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 文件名稱(繁) 的當地語系化字串。
        /// </summary>
        internal static string Label_WFDocZHTW {
            get {
                return ResourceManager.GetString("Label_WFDocZHTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程 的當地語系化字串。
        /// </summary>
        internal static string Label_WFFlow {
            get {
                return ResourceManager.GetString("Label_WFFlow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程版本 的當地語系化字串。
        /// </summary>
        internal static string Label_WFFlowVer {
            get {
                return ResourceManager.GetString("Label_WFFlowVer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程節點 的當地語系化字串。
        /// </summary>
        internal static string Label_WFNode {
            get {
                return ResourceManager.GetString("Label_WFNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程文件明細已存在 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_AddSystemWorkFlowDocumentDetailExist {
            get {
                return ResourceManager.GetString("SystemMsg_AddSystemWorkFlowDocumentDetailExist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得工作流程節點檔失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemWFNode {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemWFNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得工作流程節點列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemWorkFlowNodeIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemWorkFlowNodeIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得工作流程文件清單明細列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSystemWorkFlowDocumentDetail {
            get {
                return ResourceManager.GetString("SystemMsg_GetSystemWorkFlowDocumentDetail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得員工應用系統列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysUserSystemSysIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysUserSystemSysIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得工作流程列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysUserSystemWorkFlowIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysUserSystemWorkFlowIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您不具有使用此應用系統的權限 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_SetHasSysID {
            get {
                return ResourceManager.GetString("SystemMsg_SetHasSysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程文件明細 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemWorkFlowDocumentDetail {
            get {
                return ResourceManager.GetString("TabText_SystemWorkFlowDocumentDetail", resourceCulture);
            }
        }
    }
}
