//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別為自動產生，方法是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysSystemRecord {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysSystemRecord() {
        }
        
        /// <summary>
        ///   傳回這個類別所使用的快取 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysSystemRecord", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 只看差異內容 的當地語系化字串。
        /// </summary>
        internal static string CheckBox_IsOnlyDiffData {
            get {
                return ResourceManager.GetString("CheckBox_IsOnlyDiffData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得功能群組列表 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_GetSystemFunControllerIDList {
            get {
                return ResourceManager.GetString("JsMsg_GetSystemFunControllerIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得功能名稱列表 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_GetSystemFunNameList {
            get {
                return ResourceManager.GetString("JsMsg_GetSystemFunNameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇功能名稱 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_RequireFunActionName {
            get {
                return ResourceManager.GetString("JsMsg_RequireFunActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇功能群組 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_RequireFunControllerID {
            get {
                return ResourceManager.GetString("JsMsg_RequireFunControllerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇角色群組 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_RequireRoleGroupID {
            get {
                return ResourceManager.GetString("JsMsg_RequireRoleGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請選擇應用系統 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_RequireSysID {
            get {
                return ResourceManager.GetString("JsMsg_RequireSysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入使用者代碼 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_RequireUserID {
            get {
                return ResourceManager.GetString("JsMsg_RequireUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 條件名稱 的當地語系化字串。
        /// </summary>
        internal static string Label_ConditionID {
            get {
                return ResourceManager.GetString("Label_ConditionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料權限授權 的當地語系化字串。
        /// </summary>
        internal static string Label_DataAuthSet {
            get {
                return ResourceManager.GetString("Label_DataAuthSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 起始日期 的當地語系化字串。
        /// </summary>
        internal static string Label_DateBegin {
            get {
                return ResourceManager.GetString("Label_DateBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結束日期 的當地語系化字串。
        /// </summary>
        internal static string Label_DateEnd {
            get {
                return ResourceManager.GetString("Label_DateEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電子簽核單號 的當地語系化字串。
        /// </summary>
        internal static string Label_ErpSign {
            get {
                return ResourceManager.GetString("Label_ErpSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能名稱 的當地語系化字串。
        /// </summary>
        internal static string Label_FunActionName {
            get {
                return ResourceManager.GetString("Label_FunActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能群組 的當地語系化字串。
        /// </summary>
        internal static string Label_FunControllerID {
            get {
                return ResourceManager.GetString("Label_FunControllerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Line代碼 的當地語系化字串。
        /// </summary>
        internal static string Label_LineID {
            get {
                return ResourceManager.GetString("Label_LineID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改紀錄 的當地語系化字串。
        /// </summary>
        internal static string Label_ModifyRecord {
            get {
                return ResourceManager.GetString("Label_ModifyRecord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 紀錄檔類型 的當地語系化字串。
        /// </summary>
        internal static string Label_RecordType {
            get {
                return ResourceManager.GetString("Label_RecordType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色群組 的當地語系化字串。
        /// </summary>
        internal static string Label_RoleGroupID {
            get {
                return ResourceManager.GetString("Label_RoleGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統角色 的當地語系化字串。
        /// </summary>
        internal static string Label_RoleList {
            get {
                return ResourceManager.GetString("Label_RoleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_SysID {
            get {
                return ResourceManager.GetString("Label_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 起始時間 的當地語系化字串。
        /// </summary>
        internal static string Label_TimeBegin {
            get {
                return ResourceManager.GetString("Label_TimeBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結束時間 的當地語系化字串。
        /// </summary>
        internal static string Label_TimeEnd {
            get {
                return ResourceManager.GetString("Label_TimeEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者代碼 的當地語系化字串。
        /// </summary>
        internal static string Label_UserID {
            get {
                return ResourceManager.GetString("Label_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新時間 的當地語系化字串。
        /// </summary>
        internal static string Lable_UpdDT {
            get {
                return ResourceManager.GetString("Lable_UpdDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新人員 的當地語系化字串。
        /// </summary>
        internal static string Lable_UpdUserID {
            get {
                return ResourceManager.GetString("Lable_UpdUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得紀錄檔類型清單失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetBaseRecordTypeList {
            get {
                return ResourceManager.GetString("SystemMsg_GetBaseRecordTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得Line代碼列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetLineBotIDList_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_GetLineBotIDList_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得使用者異動紀錄檔清單失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetLogUserApplyList_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_GetLogUserApplyList_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得系統角色預設條件發生錯誤 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetRoleConditionJsonString_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_GetRoleConditionJsonString_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得條件名稱列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemConditionIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemConditionIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得功能群組列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemFunControllerIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemFunControllerIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得功能名稱應用系統列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemFunNameList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemFunNameList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得角色群組列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemRoleGroupList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemRoleGroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得應用系統列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemSysIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemSysIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得系統紀錄檔列表失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSystemRecordList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSystemRecordList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 API序號 的當地語系化字串。
        /// </summary>
        internal static string Table_APINo {
            get {
                return ResourceManager.GetString("Table_APINo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司代碼 的當地語系化字串。
        /// </summary>
        internal static string Table_ComID {
            get {
                return ResourceManager.GetString("Table_ComID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預設條件 的當地語系化字串。
        /// </summary>
        internal static string Table_Condition {
            get {
                return ResourceManager.GetString("Table_Condition", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 條件名稱 的當地語系化字串。
        /// </summary>
        internal static string Table_ConditionID {
            get {
                return ResourceManager.GetString("Table_ConditionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 明細 的當地語系化字串。
        /// </summary>
        internal static string Table_Detail {
            get {
                return ResourceManager.GetString("Table_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 電子簽核單號 的當地語系化字串。
        /// </summary>
        internal static string Table_ErpSign {
            get {
                return ResourceManager.GetString("Table_ErpSign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 執行來源IP 的當地語系化字串。
        /// </summary>
        internal static string Table_ExecIPAddress {
            get {
                return ResourceManager.GetString("Table_ExecIPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 執行來源應用系統 的當地語系化字串。
        /// </summary>
        internal static string Table_ExecSysID {
            get {
                return ResourceManager.GetString("Table_ExecSysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能名稱 的當地語系化字串。
        /// </summary>
        internal static string Table_FunActionName {
            get {
                return ResourceManager.GetString("Table_FunActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能群組 的當地語系化字串。
        /// </summary>
        internal static string Table_FunControllerID {
            get {
                return ResourceManager.GetString("Table_FunControllerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能群組名稱(英) 的當地語系化字串。
        /// </summary>
        internal static string Table_FunGroupENUS {
            get {
                return ResourceManager.GetString("Table_FunGroupENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能群組名稱(日) 的當地語系化字串。
        /// </summary>
        internal static string Table_FunGroupJAJP {
            get {
                return ResourceManager.GetString("Table_FunGroupJAJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能群組名稱(韓) 的當地語系化字串。
        /// </summary>
        internal static string Table_FunGroupKOKR {
            get {
                return ResourceManager.GetString("Table_FunGroupKOKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能群組名稱(泰) 的當地語系化字串。
        /// </summary>
        internal static string Table_FunGroupTHTH {
            get {
                return ResourceManager.GetString("Table_FunGroupTHTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能群組名稱(簡) 的當地語系化字串。
        /// </summary>
        internal static string Table_FunGroupZHCN {
            get {
                return ResourceManager.GetString("Table_FunGroupZHCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能群組名稱(繁) 的當地語系化字串。
        /// </summary>
        internal static string Table_FunGroupZHTW {
            get {
                return ResourceManager.GetString("Table_FunGroupZHTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能名稱(英) 的當地語系化字串。
        /// </summary>
        internal static string Table_FunNMENUS {
            get {
                return ResourceManager.GetString("Table_FunNMENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能名稱(日) 的當地語系化字串。
        /// </summary>
        internal static string Table_FunNMJAJP {
            get {
                return ResourceManager.GetString("Table_FunNMJAJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能名稱(韓) 的當地語系化字串。
        /// </summary>
        internal static string Table_FunNMKOKR {
            get {
                return ResourceManager.GetString("Table_FunNMKOKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能名稱(泰) 的當地語系化字串。
        /// </summary>
        internal static string Table_FunNMTHTH {
            get {
                return ResourceManager.GetString("Table_FunNMTHTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能名稱(簡) 的當地語系化字串。
        /// </summary>
        internal static string Table_FunNMZHCN {
            get {
                return ResourceManager.GetString("Table_FunNMZHCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能名稱(繁) 的當地語系化字串。
        /// </summary>
        internal static string Table_FunNMZHTW {
            get {
                return ResourceManager.GetString("Table_FunNMZHTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能類型 的當地語系化字串。
        /// </summary>
        internal static string Table_FunType {
            get {
                return ResourceManager.GetString("Table_FunType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 來源IP 的當地語系化字串。
        /// </summary>
        internal static string Table_IPAddress {
            get {
                return ResourceManager.GetString("Table_IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 起始網段 的當地語系化字串。
        /// </summary>
        internal static string Table_IPBegin {
            get {
                return ResourceManager.GetString("Table_IPBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結束網段 的當地語系化字串。
        /// </summary>
        internal static string Table_IPEnd {
            get {
                return ResourceManager.GetString("Table_IPEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否停用 的當地語系化字串。
        /// </summary>
        internal static string Table_IsDisable {
            get {
                return ResourceManager.GetString("Table_IsDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 離職 的當地語系化字串。
        /// </summary>
        internal static string Table_IsLeft {
            get {
                return ResourceManager.GetString("Table_IsLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否鎖定 的當地語系化字串。
        /// </summary>
        internal static string Table_IsLock {
            get {
                return ResourceManager.GetString("Table_IsLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否為主控 的當地語系化字串。
        /// </summary>
        internal static string Table_IsMaster {
            get {
                return ResourceManager.GetString("Table_IsMaster", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 外部使用 的當地語系化字串。
        /// </summary>
        internal static string Table_IsOutside {
            get {
                return ResourceManager.GetString("Table_IsOutside", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否重設密碼 的當地語系化字串。
        /// </summary>
        internal static string Table_IsReset {
            get {
                return ResourceManager.GetString("Table_IsReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Line代碼 的當地語系化字串。
        /// </summary>
        internal static string Table_LineID {
            get {
                return ResourceManager.GetString("Table_LineID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Line名稱(英) 的當地語系化字串。
        /// </summary>
        internal static string Table_LineNMENUS {
            get {
                return ResourceManager.GetString("Table_LineNMENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Line名稱(日) 的當地語系化字串。
        /// </summary>
        internal static string Table_LineNMJAJP {
            get {
                return ResourceManager.GetString("Table_LineNMJAJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Line名稱(韓) 的當地語系化字串。
        /// </summary>
        internal static string Table_LineNMKOKR {
            get {
                return ResourceManager.GetString("Table_LineNMKOKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Line名稱(泰) 的當地語系化字串。
        /// </summary>
        internal static string Table_LineNMTHTH {
            get {
                return ResourceManager.GetString("Table_LineNMTHTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Line名稱(簡) 的當地語系化字串。
        /// </summary>
        internal static string Table_LineNMZHCN {
            get {
                return ResourceManager.GetString("Table_LineNMZHCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Line名稱(繁) 的當地語系化字串。
        /// </summary>
        internal static string Table_LineNMZHTW {
            get {
                return ResourceManager.GetString("Table_LineNMZHTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 好友代碼 的當地語系化字串。
        /// </summary>
        internal static string Table_LineReceiverID {
            get {
                return ResourceManager.GetString("Table_LineReceiverID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 好友名稱(英) 的當地語系化字串。
        /// </summary>
        internal static string Table_LineReceiverNMENUS {
            get {
                return ResourceManager.GetString("Table_LineReceiverNMENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 好友名稱(日) 的當地語系化字串。
        /// </summary>
        internal static string Table_LineReceiverNMJAJP {
            get {
                return ResourceManager.GetString("Table_LineReceiverNMJAJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 好友名稱(韓) 的當地語系化字串。
        /// </summary>
        internal static string Table_LineReceiverNMKOKR {
            get {
                return ResourceManager.GetString("Table_LineReceiverNMKOKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 好友名稱(泰) 的當地語系化字串。
        /// </summary>
        internal static string Table_LineReceiverNMTHTH {
            get {
                return ResourceManager.GetString("Table_LineReceiverNMTHTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 好友名稱(簡) 的當地語系化字串。
        /// </summary>
        internal static string Table_LineReceiverNMZHCN {
            get {
                return ResourceManager.GetString("Table_LineReceiverNMZHCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 好友名稱(繁) 的當地語系化字串。
        /// </summary>
        internal static string Table_LineReceiverNMZHTW {
            get {
                return ResourceManager.GetString("Table_LineReceiverNMZHTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 好友類型 的當地語系化字串。
        /// </summary>
        internal static string Table_LineSourceType {
            get {
                return ResourceManager.GetString("Table_LineSourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入位置 的當地語系化字串。
        /// </summary>
        internal static string Table_Location {
            get {
                return ResourceManager.GetString("Table_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入位置說明 的當地語系化字串。
        /// </summary>
        internal static string Table_LocationDesc {
            get {
                return ResourceManager.GetString("Table_LocationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 紀錄序號 的當地語系化字串。
        /// </summary>
        internal static string Table_LogNo {
            get {
                return ResourceManager.GetString("Table_LogNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改日期 的當地語系化字串。
        /// </summary>
        internal static string Table_ModifyDate {
            get {
                return ResourceManager.GetString("Table_ModifyDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 異動類型 的當地語系化字串。
        /// </summary>
        internal static string Table_ModifyType {
            get {
                return ResourceManager.GetString("Table_ModifyType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 資料權限 的當地語系化字串。
        /// </summary>
        internal static string Table_PurviewID {
            get {
                return ResourceManager.GetString("Table_PurviewID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備註 的當地語系化字串。
        /// </summary>
        internal static string Table_Remark {
            get {
                return ResourceManager.GetString("Table_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 環境限制類型 的當地語系化字串。
        /// </summary>
        internal static string Table_RestrictType {
            get {
                return ResourceManager.GetString("Table_RestrictType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色分類 的當地語系化字串。
        /// </summary>
        internal static string Table_RoleCategoryID {
            get {
                return ResourceManager.GetString("Table_RoleCategoryID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色群組 的當地語系化字串。
        /// </summary>
        internal static string Table_RoleGroupID {
            get {
                return ResourceManager.GetString("Table_RoleGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色群組名稱(英) 的當地語系化字串。
        /// </summary>
        internal static string Table_RoleGroupNMENUS {
            get {
                return ResourceManager.GetString("Table_RoleGroupNMENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色群組名稱(日) 的當地語系化字串。
        /// </summary>
        internal static string Table_RoleGroupNMJAJP {
            get {
                return ResourceManager.GetString("Table_RoleGroupNMJAJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色群組名稱(韓) 的當地語系化字串。
        /// </summary>
        internal static string Table_RoleGroupNMKOKR {
            get {
                return ResourceManager.GetString("Table_RoleGroupNMKOKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色群組名稱(泰) 的當地語系化字串。
        /// </summary>
        internal static string Table_RoleGroupNMTHTH {
            get {
                return ResourceManager.GetString("Table_RoleGroupNMTHTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色群組名稱(簡) 的當地語系化字串。
        /// </summary>
        internal static string Table_RoleGroupNMZHCN {
            get {
                return ResourceManager.GetString("Table_RoleGroupNMZHCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色群組名稱(繁) 的當地語系化字串。
        /// </summary>
        internal static string Table_RoleGroupNMZHTW {
            get {
                return ResourceManager.GetString("Table_RoleGroupNMZHTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色 的當地語系化字串。
        /// </summary>
        internal static string Table_RoleID {
            get {
                return ResourceManager.GetString("Table_RoleID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色名單 的當地語系化字串。
        /// </summary>
        internal static string Table_RoleList {
            get {
                return ResourceManager.GetString("Table_RoleList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色名稱(英) 的當地語系化字串。
        /// </summary>
        internal static string Table_RoleNMENUS {
            get {
                return ResourceManager.GetString("Table_RoleNMENUS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色名稱(日) 的當地語系化字串。
        /// </summary>
        internal static string Table_RoleNMJAJP {
            get {
                return ResourceManager.GetString("Table_RoleNMJAJP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色名稱(韓) 的當地語系化字串。
        /// </summary>
        internal static string Table_RoleNMKOKR {
            get {
                return ResourceManager.GetString("Table_RoleNMKOKR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色名稱(泰) 的當地語系化字串。
        /// </summary>
        internal static string Table_RoleNMTHTH {
            get {
                return ResourceManager.GetString("Table_RoleNMTHTH", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色名稱(簡) 的當地語系化字串。
        /// </summary>
        internal static string Table_RoleNMZHCN {
            get {
                return ResourceManager.GetString("Table_RoleNMZHCN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 角色名稱(繁) 的當地語系化字串。
        /// </summary>
        internal static string Table_RoleNMZHTW {
            get {
                return ResourceManager.GetString("Table_RoleNMZHTW", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序 的當地語系化字串。
        /// </summary>
        internal static string Table_SortOrder {
            get {
                return ResourceManager.GetString("Table_SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 來源類型 的當地語系化字串。
        /// </summary>
        internal static string Table_SourceType {
            get {
                return ResourceManager.GetString("Table_SourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統(子系統) 的當地語系化字串。
        /// </summary>
        internal static string Table_SubSysID {
            get {
                return ResourceManager.GetString("Table_SubSysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Table_SysID {
            get {
                return ResourceManager.GetString("Table_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 信任狀態 的當地語系化字串。
        /// </summary>
        internal static string Table_TrustStatus {
            get {
                return ResourceManager.GetString("Table_TrustStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 信任類型 的當地語系化字串。
        /// </summary>
        internal static string Table_TrustType {
            get {
                return ResourceManager.GetString("Table_TrustType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新時間 的當地語系化字串。
        /// </summary>
        internal static string Table_UpdDT {
            get {
                return ResourceManager.GetString("Table_UpdDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新人員 的當地語系化字串。
        /// </summary>
        internal static string Table_UpdUserID {
            get {
                return ResourceManager.GetString("Table_UpdUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ERP-公司 的當地語系化字串。
        /// </summary>
        internal static string Table_UserCompNM {
            get {
                return ResourceManager.GetString("Table_UserCompNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者姓名 的當地語系化字串。
        /// </summary>
        internal static string Table_UserID {
            get {
                return ResourceManager.GetString("Table_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 組織-區域 的當地語系化字串。
        /// </summary>
        internal static string Table_UserOrgAreaNM {
            get {
                return ResourceManager.GetString("Table_UserOrgAreaNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 組織-部門 的當地語系化字串。
        /// </summary>
        internal static string Table_UserOrgDeptNM {
            get {
                return ResourceManager.GetString("Table_UserOrgDeptNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 組織-事業群 的當地語系化字串。
        /// </summary>
        internal static string Table_UserOrgGroupNM {
            get {
                return ResourceManager.GetString("Table_UserOrgGroupNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 組織-職等 的當地語系化字串。
        /// </summary>
        internal static string Table_UserOrgLevelNM {
            get {
                return ResourceManager.GetString("Table_UserOrgLevelNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 組織-事業處 的當地語系化字串。
        /// </summary>
        internal static string Table_UserOrgPlaceNM {
            get {
                return ResourceManager.GetString("Table_UserOrgPlaceNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 組織-業務職稱 的當地語系化字串。
        /// </summary>
        internal static string Table_UserOrgPTitle2NM {
            get {
                return ResourceManager.GetString("Table_UserOrgPTitle2NM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 組織-職稱 的當地語系化字串。
        /// </summary>
        internal static string Table_UserOrgPTitleNM {
            get {
                return ResourceManager.GetString("Table_UserOrgPTitleNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 組織-組別 的當地語系化字串。
        /// </summary>
        internal static string Table_UserOrgTeamNM {
            get {
                return ResourceManager.GetString("Table_UserOrgTeamNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 組織-職級 的當地語系化字串。
        /// </summary>
        internal static string Table_UserOrgTitleNM {
            get {
                return ResourceManager.GetString("Table_UserOrgTitleNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 組織-上班公司 的當地語系化字串。
        /// </summary>
        internal static string Table_UserOrgWorkCompNM {
            get {
                return ResourceManager.GetString("Table_UserOrgWorkCompNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ERP-組別 的當地語系化字串。
        /// </summary>
        internal static string Table_UserTeamNM {
            get {
                return ResourceManager.GetString("Table_UserTeamNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ERP-職稱 的當地語系化字串。
        /// </summary>
        internal static string Table_UserTitleNM {
            get {
                return ResourceManager.GetString("Table_UserTitleNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ERP-單位 的當地語系化字串。
        /// </summary>
        internal static string Table_UserUnitNM {
            get {
                return ResourceManager.GetString("Table_UserUnitNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ERP-工作 的當地語系化字串。
        /// </summary>
        internal static string Table_UserWorkNM {
            get {
                return ResourceManager.GetString("Table_UserWorkNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 驗證結果 的當地語系化字串。
        /// </summary>
        internal static string Table_ValidResult {
            get {
                return ResourceManager.GetString("Table_ValidResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 明細 的當地語系化字串。
        /// </summary>
        internal static string Text_Detail {
            get {
                return ResourceManager.GetString("Text_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查無相關資料 的當地語系化字串。
        /// </summary>
        internal static string Text_NoData {
            get {
                return ResourceManager.GetString("Text_NoData", resourceCulture);
            }
        }
    }
}
