//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysSystemLoginEventSetting {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysSystemLoginEventSetting() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysSystemLoginEventSetting", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 取得系統登入作業代碼失敗 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_GetSysLoginEventIDList_Failure {
            get {
                return ResourceManager.GetString("JsMsg_GetSysLoginEventIDList_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統必選 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_SysID_Required {
            get {
                return ResourceManager.GetString("JsMsg_SysID_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 明細 的當地語系化字串。
        /// </summary>
        internal static string Label_Detail {
            get {
                return ResourceManager.GetString("Label_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入作業代碼 的當地語系化字串。
        /// </summary>
        internal static string Label_LoginEventID {
            get {
                return ResourceManager.GetString("Label_LoginEventID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_SysID {
            get {
                return ResourceManager.GetString("Label_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入作業設定 的當地語系化字串。
        /// </summary>
        internal static string Label_SystemLoginEventSetting {
            get {
                return ResourceManager.GetString("Label_SystemLoginEventSetting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得系統登入作業代碼失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysLoginEventIDList_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysLoginEventIDList_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得應用系統登入作業設定清單失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysLoginEventSettingList_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysLoginEventSettingList_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得應用系統列表失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemSysIDList_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemSysIDList_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新應用系統登入作業列表排序失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_UpdateSysLoginEventSettingSortResult_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_UpdateSysLoginEventSettingSortResult_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 明細 的當地語系化字串。
        /// </summary>
        internal static string Tabel_Detail {
            get {
                return ResourceManager.GetString("Tabel_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結束時間 的當地語系化字串。
        /// </summary>
        internal static string Table_EndDT {
            get {
                return ResourceManager.GetString("Table_EndDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 是否停用 的當地語系化字串。
        /// </summary>
        internal static string Table_IsDisable {
            get {
                return ResourceManager.GetString("Table_IsDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入作業 的當地語系化字串。
        /// </summary>
        internal static string Table_LoginEventID {
            get {
                return ResourceManager.GetString("Table_LoginEventID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序 的當地語系化字串。
        /// </summary>
        internal static string Table_SortOrder {
            get {
                return ResourceManager.GetString("Table_SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始時間 的當地語系化字串。
        /// </summary>
        internal static string Table_StartDT {
            get {
                return ResourceManager.GetString("Table_StartDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 子系統 的當地語系化字串。
        /// </summary>
        internal static string Table_SubSysID {
            get {
                return ResourceManager.GetString("Table_SubSysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Table_SysID {
            get {
                return ResourceManager.GetString("Table_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新時間 的當地語系化字串。
        /// </summary>
        internal static string Table_UpdDT {
            get {
                return ResourceManager.GetString("Table_UpdDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新人員 的當地語系化字串。
        /// </summary>
        internal static string Table_UpdUserID {
            get {
                return ResourceManager.GetString("Table_UpdUserID", resourceCulture);
            }
        }
    }
}
