//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysSystemAPILog {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysSystemAPILog() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysSystemAPILog", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 開始日期不能大於結束日期 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_Date_Error {
            get {
                return ResourceManager.GetString("JsMsg_Date_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入正確時間格式 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_HHmm_Error {
            get {
                return ResourceManager.GetString("JsMsg_HHmm_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 時間範圍為1小時內 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_TimeInterval_Error {
            get {
                return ResourceManager.GetString("JsMsg_TimeInterval_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得API功能列表 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_UnGetSysSystemAPIByIdList {
            get {
                return ResourceManager.GetString("JsMsg_UnGetSysSystemAPIByIdList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得API群組選單 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_UnGetSysSystemAPIGroupByIdList {
            get {
                return ResourceManager.GetString("JsMsg_UnGetSysSystemAPIGroupByIdList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 API功能 的當地語系化字串。
        /// </summary>
        internal static string Label_APIFunID {
            get {
                return ResourceManager.GetString("Label_APIFunID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 API群組 的當地語系化字串。
        /// </summary>
        internal static string Label_APIGroupID {
            get {
                return ResourceManager.GetString("Label_APIGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 API序號 的當地語系化字串。
        /// </summary>
        internal static string Label_APINo {
            get {
                return ResourceManager.GetString("Label_APINo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始時間 的當地語系化字串。
        /// </summary>
        internal static string Label_BeginTime {
            get {
                return ResourceManager.GetString("Label_BeginTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始作業時間 的當地語系化字串。
        /// </summary>
        internal static string Label_ClientDTBegin {
            get {
                return ResourceManager.GetString("Label_ClientDTBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結束作業時間 的當地語系化字串。
        /// </summary>
        internal static string Label_ClientDTEnd {
            get {
                return ResourceManager.GetString("Label_ClientDTEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 授權系統 的當地語系化字串。
        /// </summary>
        internal static string Label_ClientSysID {
            get {
                return ResourceManager.GetString("Label_ClientSysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始日期 的當地語系化字串。
        /// </summary>
        internal static string Label_DTBegin {
            get {
                return ResourceManager.GetString("Label_DTBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結束日期 的當地語系化字串。
        /// </summary>
        internal static string Label_DTEnd {
            get {
                return ResourceManager.GetString("Label_DTEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結束時間 的當地語系化字串。
        /// </summary>
        internal static string Label_EndTime {
            get {
                return ResourceManager.GetString("Label_EndTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 來源IP 的當地語系化字串。
        /// </summary>
        internal static string Label_IPAddress {
            get {
                return ResourceManager.GetString("Label_IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_SysID {
            get {
                return ResourceManager.GetString("Label_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得API功能選單 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_UnGetSysSystemAPIByIdList {
            get {
                return ResourceManager.GetString("SystemMsg_UnGetSysSystemAPIByIdList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得API群組選單 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_UnGetSysSystemAPIGroupByIdList {
            get {
                return ResourceManager.GetString("SystemMsg_UnGetSysSystemAPIGroupByIdList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得API紀錄列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_UnGetSystemAPILogList {
            get {
                return ResourceManager.GetString("SystemMsg_UnGetSystemAPILogList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得授權系統選單 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_UnGetSystemByIdList {
            get {
                return ResourceManager.GetString("SystemMsg_UnGetSystemByIdList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得應用系統選單 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_UnGetUserSystemByIdList {
            get {
                return ResourceManager.GetString("SystemMsg_UnGetUserSystemByIdList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 紀錄 的當地語系化字串。
        /// </summary>
        internal static string Text_APILog {
            get {
                return ResourceManager.GetString("Text_APILog", resourceCulture);
            }
        }
    }
}
