//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysSystemWorkFlowGroup {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysSystemWorkFlowGroup() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysSystemWorkFlowGroup", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 排序 的當地語系化字串。
        /// </summary>
        internal static string Label_SortOrder {
            get {
                return ResourceManager.GetString("Label_SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_SysID {
            get {
                return ResourceManager.GetString("Label_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新時間 的當地語系化字串。
        /// </summary>
        internal static string Label_UpdDT {
            get {
                return ResourceManager.GetString("Label_UpdDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新人員 的當地語系化字串。
        /// </summary>
        internal static string Label_UpdUserNM {
            get {
                return ResourceManager.GetString("Label_UpdUserNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程群組 的當地語系化字串。
        /// </summary>
        internal static string Label_WFFlowGroupID {
            get {
                return ResourceManager.GetString("Label_WFFlowGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得應用系統列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSystemSysIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSystemSysIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得工作流程群組列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSystemWorkFlowGroupList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSystemWorkFlowGroupList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得員工應用系統列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysUserSystemSysIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysUserSystemSysIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程群組排序儲存錯誤 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_SaveWorkFlowGroupSortOrderError {
            get {
                return ResourceManager.GetString("SystemMsg_SaveWorkFlowGroupSortOrderError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序 的當地語系化字串。
        /// </summary>
        internal static string Table_SortOrder {
            get {
                return ResourceManager.GetString("Table_SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Table_SysID {
            get {
                return ResourceManager.GetString("Table_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新時間 的當地語系化字串。
        /// </summary>
        internal static string Table_UpdDT {
            get {
                return ResourceManager.GetString("Table_UpdDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新人員 的當地語系化字串。
        /// </summary>
        internal static string Table_UpdUserID {
            get {
                return ResourceManager.GetString("Table_UpdUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新人員 的當地語系化字串。
        /// </summary>
        internal static string Table_UpdUserNM {
            get {
                return ResourceManager.GetString("Table_UpdUserNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程群組代碼 的當地語系化字串。
        /// </summary>
        internal static string Table_WFFlowGroupID {
            get {
                return ResourceManager.GetString("Table_WFFlowGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程群組 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemWorkFlowGroup {
            get {
                return ResourceManager.GetString("TabText_SystemWorkFlowGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 連線字串檔 的當地語系化字串。
        /// </summary>
        internal static string Text_Con {
            get {
                return ResourceManager.GetString("Text_Con", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 明細 的當地語系化字串。
        /// </summary>
        internal static string Text_Detail {
            get {
                return ResourceManager.GetString("Text_Detail", resourceCulture);
            }
        }
    }
}
