//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysSystemWorkFlowNext {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysSystemWorkFlowNext() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysSystemWorkFlowNext", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 取得工作流程群組列表失敗 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_GetSysSystemWorkFlowGroupIDList {
            get {
                return ResourceManager.GetString("JsMsg_GetSysSystemWorkFlowGroupIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得工作流程節點列表失敗 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_GetSysSystemWorkFlowNodeIDList {
            get {
                return ResourceManager.GetString("JsMsg_GetSysSystemWorkFlowNodeIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得工作流程列表失敗 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_GetSysUserSystemWorkFlowIDList {
            get {
                return ResourceManager.GetString("JsMsg_GetSysUserSystemWorkFlowIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 在執行新增動作時，工作流程：必須選取 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_WFCombineKeyIsEmpty {
            get {
                return ResourceManager.GetString("JsMsg_WFCombineKeyIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 在執行新增動作時，工作流程群組：必須選取 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_WFFlowGroupIDIsEmpty {
            get {
                return ResourceManager.GetString("JsMsg_WFFlowGroupIDIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 在執行新增動作時，工作流程節點：必須選取 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_WFNodeIDIsEmpty {
            get {
                return ResourceManager.GetString("JsMsg_WFNodeIDIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 ＊若本節點的節點類型為作業節點(P)時，次節點檔只可有一筆資料 的當地語系化字串。
        /// </summary>
        internal static string Label_NodeTypeMemo {
            get {
                return ResourceManager.GetString("Label_NodeTypeMemo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_SysID {
            get {
                return ResourceManager.GetString("Label_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程群組 的當地語系化字串。
        /// </summary>
        internal static string Label_WFFlowGroupID {
            get {
                return ResourceManager.GetString("Label_WFFlowGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程 的當地語系化字串。
        /// </summary>
        internal static string Label_WFFlowID {
            get {
                return ResourceManager.GetString("Label_WFFlowID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程節點 的當地語系化字串。
        /// </summary>
        internal static string Label_WFFlowNodeID {
            get {
                return ResourceManager.GetString("Label_WFFlowNodeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得工作流程節點檔失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemWFNode {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemWFNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得工作流程次節點檔失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSystemWFNextList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSystemWFNextList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得員工應用系統列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysUserSystemSysIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysUserSystemSysIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序儲存錯誤 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetWorkFlowNextSettingResult {
            get {
                return ResourceManager.GetString("SystemMsg_GetWorkFlowNextSettingResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 明細 的當地語系化字串。
        /// </summary>
        internal static string Table_Detail {
            get {
                return ResourceManager.GetString("Table_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能名稱 的當地語系化字串。
        /// </summary>
        internal static string Table_FunActionNameNM {
            get {
                return ResourceManager.GetString("Table_FunActionNameNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能群組 的當地語系化字串。
        /// </summary>
        internal static string Table_FunControllerNM {
            get {
                return ResourceManager.GetString("Table_FunControllerNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能應用系統 的當地語系化字串。
        /// </summary>
        internal static string Table_FunSysNM {
            get {
                return ResourceManager.GetString("Table_FunSysNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 節點類型 的當地語系化字串。
        /// </summary>
        internal static string Table_NextNodeTypeNM {
            get {
                return ResourceManager.GetString("Table_NextNodeTypeNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 判斷條件 的當地語系化字串。
        /// </summary>
        internal static string Table_NextResultValue {
            get {
                return ResourceManager.GetString("Table_NextResultValue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 下一節點 的當地語系化字串。
        /// </summary>
        internal static string Table_NextWFNodeID {
            get {
                return ResourceManager.GetString("Table_NextWFNodeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序 的當地語系化字串。
        /// </summary>
        internal static string Table_SortOrder {
            get {
                return ResourceManager.GetString("Table_SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能應用系統(子系統) 的當地語系化字串。
        /// </summary>
        internal static string Table_SubSysNM {
            get {
                return ResourceManager.GetString("Table_SubSysNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Table_SysID {
            get {
                return ResourceManager.GetString("Table_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新時間 的當地語系化字串。
        /// </summary>
        internal static string Table_UpdDt {
            get {
                return ResourceManager.GetString("Table_UpdDt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新人員 的當地語系化字串。
        /// </summary>
        internal static string Table_UpdUserNM {
            get {
                return ResourceManager.GetString("Table_UpdUserNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程群組 的當地語系化字串。
        /// </summary>
        internal static string Table_WFFlowGroupID {
            get {
                return ResourceManager.GetString("Table_WFFlowGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程 的當地語系化字串。
        /// </summary>
        internal static string Table_WFFlowID {
            get {
                return ResourceManager.GetString("Table_WFFlowID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程節點 的當地語系化字串。
        /// </summary>
        internal static string Table_WFFlowNodeID {
            get {
                return ResourceManager.GetString("Table_WFFlowNodeID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 工作流程版本 的當地語系化字串。
        /// </summary>
        internal static string Table_WFFlowVer {
            get {
                return ResourceManager.GetString("Table_WFFlowVer", resourceCulture);
            }
        }
    }
}
