//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysTrustIP {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysTrustIP() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysTrustIP", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 公司代碼 的當地語系化字串。
        /// </summary>
        internal static string Label_ComID {
            get {
                return ResourceManager.GetString("Label_ComID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 起始網段 的當地語系化字串。
        /// </summary>
        internal static string Label_IPBegin {
            get {
                return ResourceManager.GetString("Label_IPBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結束網段 的當地語系化字串。
        /// </summary>
        internal static string Label_IPEnd {
            get {
                return ResourceManager.GetString("Label_IPEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備註 的當地語系化字串。
        /// </summary>
        internal static string Label_Remark {
            get {
                return ResourceManager.GetString("Label_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 來源類型 的當地語系化字串。
        /// </summary>
        internal static string Label_SourceType {
            get {
                return ResourceManager.GetString("Label_SourceType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 只查信任 的當地語系化字串。
        /// </summary>
        internal static string Label_TrustStatus {
            get {
                return ResourceManager.GetString("Label_TrustStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 信任類型 的當地語系化字串。
        /// </summary>
        internal static string Label_TrustType {
            get {
                return ResourceManager.GetString("Label_TrustType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得公司代碼列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetBaseRawCMOrgComList {
            get {
                return ResourceManager.GetString("SystemMsg_GetBaseRawCMOrgComList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得來源類型列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetBaseSourceTypeList {
            get {
                return ResourceManager.GetString("SystemMsg_GetBaseSourceTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得信任類型列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetBaseTrustTypeList {
            get {
                return ResourceManager.GetString("SystemMsg_GetBaseTrustTypeList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得信任網段清單失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetTrustIPList {
            get {
                return ResourceManager.GetString("SystemMsg_GetTrustIPList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司代碼 的當地語系化字串。
        /// </summary>
        internal static string Table_ComNM {
            get {
                return ResourceManager.GetString("Table_ComNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 起始網段 的當地語系化字串。
        /// </summary>
        internal static string Table_IPBegin {
            get {
                return ResourceManager.GetString("Table_IPBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結束網段 的當地語系化字串。
        /// </summary>
        internal static string Table_IPEnd {
            get {
                return ResourceManager.GetString("Table_IPEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備註 的當地語系化字串。
        /// </summary>
        internal static string Table_Remark {
            get {
                return ResourceManager.GetString("Table_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 排序 的當地語系化字串。
        /// </summary>
        internal static string Table_SortOrder {
            get {
                return ResourceManager.GetString("Table_SortOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 來源類型 的當地語系化字串。
        /// </summary>
        internal static string Table_SourceTypeNM {
            get {
                return ResourceManager.GetString("Table_SourceTypeNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 信任狀態 的當地語系化字串。
        /// </summary>
        internal static string Table_TrustStatus {
            get {
                return ResourceManager.GetString("Table_TrustStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 信任類型 的當地語系化字串。
        /// </summary>
        internal static string Table_TrustTypeNM {
            get {
                return ResourceManager.GetString("Table_TrustTypeNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新時間 的當地語系化字串。
        /// </summary>
        internal static string Table_UpdDT {
            get {
                return ResourceManager.GetString("Table_UpdDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新人員 的當地語系化字串。
        /// </summary>
        internal static string Table_UpdUserNM {
            get {
                return ResourceManager.GetString("Table_UpdUserNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 信任網段 的當地語系化字串。
        /// </summary>
        internal static string TabText_TrustIP {
            get {
                return ResourceManager.GetString("TabText_TrustIP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 明細 的當地語系化字串。
        /// </summary>
        internal static string Text_Detail {
            get {
                return ResourceManager.GetString("Text_Detail", resourceCulture);
            }
        }
    }
}
