//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SysUserDomain {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SysUserDomain() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.SysUserDomain", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 網域帳號 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_DomainAccount {
            get {
                return ResourceManager.GetString("JsMsg_DomainAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 網域群組 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_DomainGroupID {
            get {
                return ResourceManager.GetString("JsMsg_DomainGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 網域名稱 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_DomainName {
            get {
                return ResourceManager.GetString("JsMsg_DomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密码必填 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_LoginPWD_Required {
            get {
                return ResourceManager.GetString("JsMsg_LoginPWD_Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入失败 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_Login_Failure {
            get {
                return ResourceManager.GetString("JsMsg_Login_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 網域群組 的當地語系化字串。
        /// </summary>
        internal static string Label_DomainGroupID {
            get {
                return ResourceManager.GetString("Label_DomainGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 網域名稱 的當地語系化字串。
        /// </summary>
        internal static string Label_DomainName {
            get {
                return ResourceManager.GetString("Label_DomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入密碼 的當地語系化字串。
        /// </summary>
        internal static string Label_LoginPWD {
            get {
                return ResourceManager.GetString("Label_LoginPWD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者代碼 的當地語系化字串。
        /// </summary>
        internal static string Label_UserID {
            get {
                return ResourceManager.GetString("Label_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者姓名 的當地語系化字串。
        /// </summary>
        internal static string Label_UserNM {
            get {
                return ResourceManager.GetString("Label_UserNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得使用者網域列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysUserDomainList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysUserDomainList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 明細 的當地語系化字串。
        /// </summary>
        internal static string Text_Detail {
            get {
                return ResourceManager.GetString("Text_Detail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 網域帳號 的當地語系化字串。
        /// </summary>
        internal static string Text_DomainAccount {
            get {
                return ResourceManager.GetString("Text_DomainAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 網域群組 的當地語系化字串。
        /// </summary>
        internal static string Text_DomainGroupID {
            get {
                return ResourceManager.GetString("Text_DomainGroupID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 網域名稱 的當地語系化字串。
        /// </summary>
        internal static string Text_DomainName {
            get {
                return ResourceManager.GetString("Text_DomainName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新時間 的當地語系化字串。
        /// </summary>
        internal static string Text_UpdDT {
            get {
                return ResourceManager.GetString("Text_UpdDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新人員 的當地語系化字串。
        /// </summary>
        internal static string Text_UpdUserID {
            get {
                return ResourceManager.GetString("Text_UpdUserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 部門 的當地語系化字串。
        /// </summary>
        internal static string Text_UserDept {
            get {
                return ResourceManager.GetString("Text_UserDept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 事業群 的當地語系化字串。
        /// </summary>
        internal static string Text_UserGroup {
            get {
                return ResourceManager.GetString("Text_UserGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者代碼 的當地語系化字串。
        /// </summary>
        internal static string Text_UserID {
            get {
                return ResourceManager.GetString("Text_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者姓名 的當地語系化字串。
        /// </summary>
        internal static string Text_UserNM {
            get {
                return ResourceManager.GetString("Text_UserNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 事業處 的當地語系化字串。
        /// </summary>
        internal static string Text_UserPlace {
            get {
                return ResourceManager.GetString("Text_UserPlace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 組別 的當地語系化字串。
        /// </summary>
        internal static string Text_UserTeam {
            get {
                return ResourceManager.GetString("Text_UserTeam", resourceCulture);
            }
        }
    }
}
