//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class HomeIndex {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal HomeIndex() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.HomeIndex", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 出生日期 的當地語系化字串。
        /// </summary>
        internal static string Label_Birthday {
            get {
                return ResourceManager.GetString("Label_Birthday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 大寫鎖定中，請留意輸入資訊的正確性 的當地語系化字串。
        /// </summary>
        internal static string Label_CapsLockRemind {
            get {
                return ResourceManager.GetString("Label_CapsLockRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 多國語系 的當地語系化字串。
        /// </summary>
        internal static string Label_CultureID {
            get {
                return ResourceManager.GetString("Label_CultureID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 身份證字號 的當地語系化字串。
        /// </summary>
        internal static string Label_IdNo {
            get {
                return ResourceManager.GetString("Label_IdNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 在同行 的當地語系化字串。
        /// </summary>
        internal static string Label_InAgent {
            get {
                return ResourceManager.GetString("Label_InAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公司 的當地語系化字串。
        /// </summary>
        internal static string Label_InCompany {
            get {
                return ResourceManager.GetString("Label_InCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 在家 的當地語系化字串。
        /// </summary>
        internal static string Label_InHome {
            get {
                return ResourceManager.GetString("Label_InHome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 其他地 的當地語系化字串。
        /// </summary>
        internal static string Label_InOther {
            get {
                return ResourceManager.GetString("Label_InOther", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 您現在在： 的當地語系化字串。
        /// </summary>
        internal static string Label_Location {
            get {
                return ResourceManager.GetString("Label_Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 登入 的當地語系化字串。
        /// </summary>
        internal static string Label_Login {
            get {
                return ResourceManager.GetString("Label_Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 不在公司時請再輸入： 的當地語系化字串。
        /// </summary>
        internal static string Label_NotInCompany {
            get {
                return ResourceManager.GetString("Label_NotInCompany", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者代碼 的當地語系化字串。
        /// </summary>
        internal static string Label_UserID {
            get {
                return ResourceManager.GetString("Label_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 通行碼 的當地語系化字串。
        /// </summary>
        internal static string Label_UserPassword {
            get {
                return ResourceManager.GetString("Label_UserPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 密碼或資料錯誤!! 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_B2PAuthenticatingError {
            get {
                return ResourceManager.GetString("SystemMsg_B2PAuthenticatingError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得多國語系列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetBaseCultureIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetBaseCultureIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 員工代號不存在!! 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_UserInformationError {
            get {
                return ResourceManager.GetString("SystemMsg_UserInformationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 這是測試機 的當地語系化字串。
        /// </summary>
        internal static string Text_EnvironmentRemind {
            get {
                return ResourceManager.GetString("Text_EnvironmentRemind", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 雄獅報報 的當地語系化字串。
        /// </summary>
        internal static string Text_LionToday {
            get {
                return ResourceManager.GetString("Text_LionToday", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 網路行銷 的當地語系化字串。
        /// </summary>
        internal static string Text_Marketing {
            get {
                return ResourceManager.GetString("Text_Marketing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 公關訊息 的當地語系化字串。
        /// </summary>
        internal static string Text_PublicRelationship {
            get {
                return ResourceManager.GetString("Text_PublicRelationship", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 文章分享 的當地語系化字串。
        /// </summary>
        internal static string Text_Sharing {
            get {
                return ResourceManager.GetString("Text_Sharing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 影音分享 的當地語系化字串。
        /// </summary>
        internal static string Text_Video {
            get {
                return ResourceManager.GetString("Text_Video", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 在同行：請輸入同行公司代號 的當地語系化字串。
        /// </summary>
        internal static string Title_InAgent {
            get {
                return ResourceManager.GetString("Title_InAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 其他地：請簡要輸入您的所在地 的當地語系化字串。
        /// </summary>
        internal static string Title_InOther {
            get {
                return ResourceManager.GetString("Title_InOther", resourceCulture);
            }
        }
    }
}
