//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class PubLogUserTraceAction {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal PubLogUserTraceAction() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.PubLogUserTraceAction", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入正確時間格式 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_HHmm_Error {
            get {
                return ResourceManager.GetString("JsMsg_HHmm_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入必填欄位 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_Required_Error {
            get {
                return ResourceManager.GetString("JsMsg_Required_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢時間範圍請在一小時內 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_TraceDateRange_Error {
            get {
                return ResourceManager.GetString("JsMsg_TraceDateRange_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始日期不能大於結束日期 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_TraceDate_Error {
            get {
                return ResourceManager.GetString("JsMsg_TraceDate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能名稱 的當地語系化字串。
        /// </summary>
        internal static string Label_ActionName {
            get {
                return ResourceManager.GetString("Label_ActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能群組 的當地語系化字串。
        /// </summary>
        internal static string Label_ControllerName {
            get {
                return ResourceManager.GetString("Label_ControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結束日期 的當地語系化字串。
        /// </summary>
        internal static string Label_EndTraceDate {
            get {
                return ResourceManager.GetString("Label_EndTraceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 結束時間 的當地語系化字串。
        /// </summary>
        internal static string Label_EndTraceTime {
            get {
                return ResourceManager.GetString("Label_EndTraceTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者行為紀錄 的當地語系化字串。
        /// </summary>
        internal static string Label_LogUserTraceAction {
            get {
                return ResourceManager.GetString("Label_LogUserTraceAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Request Session ID 的當地語系化字串。
        /// </summary>
        internal static string Label_RequestSessionID {
            get {
                return ResourceManager.GetString("Label_RequestSessionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 搜尋類型 的當地語系化字串。
        /// </summary>
        internal static string Label_SearchType {
            get {
                return ResourceManager.GetString("Label_SearchType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 搜尋類型A 的當地語系化字串。
        /// </summary>
        internal static string Label_SearchTypeA {
            get {
                return ResourceManager.GetString("Label_SearchTypeA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 搜尋類型B 的當地語系化字串。
        /// </summary>
        internal static string Label_SearchTypeB {
            get {
                return ResourceManager.GetString("Label_SearchTypeB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 搜尋類型C 的當地語系化字串。
        /// </summary>
        internal static string Label_SearchTypeC {
            get {
                return ResourceManager.GetString("Label_SearchTypeC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 Session ID 的當地語系化字串。
        /// </summary>
        internal static string Label_SessionID {
            get {
                return ResourceManager.GetString("Label_SessionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始日期 的當地語系化字串。
        /// </summary>
        internal static string Label_StartTraceDate {
            get {
                return ResourceManager.GetString("Label_StartTraceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始時間 的當地語系化字串。
        /// </summary>
        internal static string Label_StartTraceTime {
            get {
                return ResourceManager.GetString("Label_StartTraceTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_SysID {
            get {
                return ResourceManager.GetString("Label_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者名稱 的當地語系化字串。
        /// </summary>
        internal static string Label_UserID {
            get {
                return ResourceManager.GetString("Label_UserID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 取得行為紀錄清單失敗 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetLogUserTraceActionList_Failure {
            get {
                return ResourceManager.GetString("SystemMsg_GetLogUserTraceActionList_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請輸入必填欄位 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_Required_Error {
            get {
                return ResourceManager.GetString("SystemMsg_Required_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 查詢時間範圍請在一小時內 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_TraceDateRange_Error {
            get {
                return ResourceManager.GetString("SystemMsg_TraceDateRange_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開始日期不能大於結束日期 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_TraceDate_Error {
            get {
                return ResourceManager.GetString("SystemMsg_TraceDate_Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能名稱 的當地語系化字串。
        /// </summary>
        internal static string Table_ActionName {
            get {
                return ResourceManager.GetString("Table_ActionName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能群組 的當地語系化字串。
        /// </summary>
        internal static string Table_ControllerName {
            get {
                return ResourceManager.GetString("Table_ControllerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請求時間 的當地語系化字串。
        /// </summary>
        internal static string Table_RequestDateTime {
            get {
                return ResourceManager.GetString("Table_RequestDateTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能路徑 的當地語系化字串。
        /// </summary>
        internal static string Table_RequestUrl {
            get {
                return ResourceManager.GetString("Table_RequestUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 SessionID 的當地語系化字串。
        /// </summary>
        internal static string Table_SessionID {
            get {
                return ResourceManager.GetString("Table_SessionID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Table_SysID {
            get {
                return ResourceManager.GetString("Table_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者 的當地語系化字串。
        /// </summary>
        internal static string Table_User {
            get {
                return ResourceManager.GetString("Table_User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 使用者IP 的當地語系化字串。
        /// </summary>
        internal static string Table_UsetIpAddress {
            get {
                return ResourceManager.GetString("Table_UsetIpAddress", resourceCulture);
            }
        }
    }
}
