//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevFunIssue {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevFunIssue() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevFunIssue", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 新增功能開發時程失敗 的當地語系化字串。
        /// </summary>
        internal static string AddFunIssueResult_Failure {
            get {
                return ResourceManager.GetString("AddFunIssueResult_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 請先選取要處理的資料 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_PickData {
            get {
                return ResourceManager.GetString("JsMsg_PickData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開發階段 的當地語系化字串。
        /// </summary>
        internal static string Label_DevPhaseNM {
            get {
                return ResourceManager.GetString("Label_DevPhaseNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 事件 的當地語系化字串。
        /// </summary>
        internal static string Label_Event {
            get {
                return ResourceManager.GetString("Label_Event", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能群組 的當地語系化字串。
        /// </summary>
        internal static string Label_FunGroup {
            get {
                return ResourceManager.GetString("Label_FunGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 程式名稱 的當地語系化字串。
        /// </summary>
        internal static string Label_FunNM {
            get {
                return ResourceManager.GetString("Label_FunNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能類型 的當地語系化字串。
        /// </summary>
        internal static string Label_FunTypeNM {
            get {
                return ResourceManager.GetString("Label_FunTypeNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 停用 的當地語系化字串。
        /// </summary>
        internal static string Label_IsDisable {
            get {
                return ResourceManager.GetString("Label_IsDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 議題編號 的當地語系化字串。
        /// </summary>
        internal static string Label_IssueNo {
            get {
                return ResourceManager.GetString("Label_IssueNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備註 的當地語系化字串。
        /// </summary>
        internal static string Label_Remark {
            get {
                return ResourceManager.GetString("Label_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 系統平台 的當地語系化字串。
        /// </summary>
        internal static string Label_SysNM {
            get {
                return ResourceManager.GetString("Label_SysNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 讀取功能問題/議題發生錯誤。請洽資訊人員。 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetFunIssueList {
            get {
                return ResourceManager.GetString("SystemMsg_GetFunIssueList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得功能資訊 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSystemFunInfor {
            get {
                return ResourceManager.GetString("SystemMsg_GetSystemFunInfor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 議題編號 的當地語系化字串。
        /// </summary>
        internal static string Table_IssueNo {
            get {
                return ResourceManager.GetString("Table_IssueNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 備註 的當地語系化字串。
        /// </summary>
        internal static string Table_Remark {
            get {
                return ResourceManager.GetString("Table_Remark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新時間 的當地語系化字串。
        /// </summary>
        internal static string Table_UpdDT {
            get {
                return ResourceManager.GetString("Table_UpdDT", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 更新人員 的當地語系化字串。
        /// </summary>
        internal static string Table_UpdUserNM {
            get {
                return ResourceManager.GetString("Table_UpdUserNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能問題/議題 的當地語系化字串。
        /// </summary>
        internal static string TabText_FunIssue {
            get {
                return ResourceManager.GetString("TabText_FunIssue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 修改功能問題/議題失敗 的當地語系化字串。
        /// </summary>
        internal static string UpdateUserFunIssueResult_Failure {
            get {
                return ResourceManager.GetString("UpdateUserFunIssueResult_Failure", resourceCulture);
            }
        }
    }
}
