//------------------------------------------------------------------------------
// <auto-generated>
//     這段程式碼是由工具產生的。
//     執行階段版本:4.0.30319.42000
//
//     對這個檔案所做的變更可能會造成錯誤的行為，而且如果重新產生程式碼，
//     變更將會遺失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   用於查詢當地語系化字串等的強型別資源類別。
    /// </summary>
    // 這個類別是自動產生的，是利用 StronglyTypedResourceBuilder
    // 類別透過 ResGen 或 Visual Studio 這類工具產生。
    // 若要加入或移除成員，請編輯您的 .ResX 檔，然後重新執行 ResGen
    // (利用 /str 選項)，或重建 Visual Studio 專案。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DevSystemFun {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DevSystemFun() {
        }
        
        /// <summary>
        ///   傳回這個類別使用的快取的 ResourceManager 執行個體。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.DevSystemFun", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   覆寫目前執行緒的 CurrentUICulture 屬性，對象是所有
        ///   使用這個強型別資源類別的資源查閱。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得功能群組列表 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_GetSystemFunControllerIDList {
            get {
                return ResourceManager.GetString("JsMsg_GetSystemFunControllerIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得功能選單列表 的當地語系化字串。
        /// </summary>
        internal static string JsMsg_GetSystemFunMenuList {
            get {
                return ResourceManager.GetString("JsMsg_GetSystemFunMenuList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能群組 的當地語系化字串。
        /// </summary>
        internal static string Label_FunControllerID {
            get {
                return ResourceManager.GetString("Label_FunControllerID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能選單 的當地語系化字串。
        /// </summary>
        internal static string Label_FunMenu {
            get {
                return ResourceManager.GetString("Label_FunMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能選單應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_FunMenuSysID {
            get {
                return ResourceManager.GetString("Label_FunMenuSysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 只查事件 的當地語系化字串。
        /// </summary>
        internal static string Label_OnlyEvent {
            get {
                return ResourceManager.GetString("Label_OnlyEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Label_SysID {
            get {
                return ResourceManager.GetString("Label_SysID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得功能群組列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemFunControllerIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemFunControllerIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得功能選單列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemFunMenuList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemFunMenuList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得功能選單應用系統列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysSystemSysIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysSystemSysIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得功能清單列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSystemFunList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSystemFunList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 無法取得應用系統列表 的當地語系化字串。
        /// </summary>
        internal static string SystemMsg_GetSysUserSystemSysIDList {
            get {
                return ResourceManager.GetString("SystemMsg_GetSysUserSystemSysIDList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 實際日期 的當地語系化字串。
        /// </summary>
        internal static string Table_ActDate {
            get {
                return ResourceManager.GetString("Table_ActDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 實際工作小時 的當地語系化字串。
        /// </summary>
        internal static string Table_ActWorkHours {
            get {
                return ResourceManager.GetString("Table_ActWorkHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開發階段 的當地語系化字串。
        /// </summary>
        internal static string Table_DevPhaseNM {
            get {
                return ResourceManager.GetString("Table_DevPhaseNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能群組 的當地語系化字串。
        /// </summary>
        internal static string Table_FunGroup {
            get {
                return ResourceManager.GetString("Table_FunGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能名稱 的當地語系化字串。
        /// </summary>
        internal static string Table_FunNM {
            get {
                return ResourceManager.GetString("Table_FunNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 功能類型 的當地語系化字串。
        /// </summary>
        internal static string Table_FunTypeNM {
            get {
                return ResourceManager.GetString("Table_FunTypeNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 停用 的當地語系化字串。
        /// </summary>
        internal static string Table_IsDisable {
            get {
                return ResourceManager.GetString("Table_IsDisable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預定日期 的當地語系化字串。
        /// </summary>
        internal static string Table_PreDate {
            get {
                return ResourceManager.GetString("Table_PreDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 預定工作小時 的當地語系化字串。
        /// </summary>
        internal static string Table_PreWorkHours {
            get {
                return ResourceManager.GetString("Table_PreWorkHours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 應用系統 的當地語系化字串。
        /// </summary>
        internal static string Table_SysNM {
            get {
                return ResourceManager.GetString("Table_SysNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 負責人員 的當地語系化字串。
        /// </summary>
        internal static string Table_UserNM {
            get {
                return ResourceManager.GetString("Table_UserNM", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 開發功能清單 的當地語系化字串。
        /// </summary>
        internal static string TabText_SystemFun {
            get {
                return ResourceManager.GetString("TabText_SystemFun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查詢類似 明細 的當地語系化字串。
        /// </summary>
        internal static string Text_Detail {
            get {
                return ResourceManager.GetString("Text_Detail", resourceCulture);
            }
        }
    }
}
